### ISSUE TITLE
Code completion, find references and go to definition not working on large org

### ISSUE THREAD

**Issue by ClemABT** [forcedotcom/salesforcedx-vscode#1299]
### Summary

When using VS Code with Salesforce plugin on a large org, the code completion, find references and go to definition is not working. The test panel is also empty.

### Steps To Reproduce:

1.  Create a project and get source code from a large org.
1.  Right click on a method and select Find all references or Go to Definition.

### Expected result

The reference panel should show corresponding references or the editor should open the definition.

### Actual result

The panel remains empty and the Apex Language Server console is displaying the following error :
```
GRAVE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at sun.misc.IOUtils.readFully(Unknown Source)
	at java.util.jar.JarFile.getBytes(Unknown Source)
	at java.util.jar.JarFile.getManifestFromReference(Unknown Source)
	at java.util.jar.JarFile.getManifest(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jdt.internal.core.nd.field.FieldSearchIndex.asList(FieldSearchIndex.java:300)
	at apex.jorje.lsp.impl.index.ApexIndex.getTestMethods(ApexIndex.java:247)
	at apex.jorje.lsp.impl.tests.StandardTestService.getTestMethods(StandardTestService.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$129/13276447.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
```
### Additional information

The issue seems related to #1103 and #1101. I get this issue since 3 days only with large org (500 classes, 50 triggers, 180 pages, 380 tests) but not with SFDX small projects.

**VS Code Version**: 1.33.1

**SFDX CLI Version**: 45.12.1

**OS and version**: Windows 10 Enterprise Version 10.0.15063

**Comment by TwistyPop** [comment]
+1, Experiencing the same issue

**Comment by TwistyPop** [comment]
+1, Experiencing the same issue
VS Code: 1.31.1
Salesforce CLI 45.14.0
Salesforce Extension Pack 45.14.0
OS Windows 10 Enterprise V 10.0.17134 Build 17134

The error renders the plugin completely useless when the apex language server crashes. Consider making the heap allocation setting for java configurable?

**Comment by ClemABT** [comment]
I have set up a new computer, connect VS Code to the same org, and I have now the code completion working, reference and tests working. So maybe there is an issue with some local description file.

**Comment by praksb** [comment]
@ClemABT There is a known perf issue that happens at startup when we index the classes in the org. Indexer takes a lot of memory at the moment. It is possible your new computer has better hardware which caused the OOM error to go away.

**Comment by cam2982** [comment]
We have the same error on large project. The same configuration of visual studio code works well with a small org. When Salesforce Pack Extension is working cpu is 100%. In very important to fix this problem because is impossible tu use VSC with big clients.

**Comment by ersi8906** [comment]
Same problem here. The extension gets unusable configuring large projects

**Comment by prudev** [comment]
I'm having the same issues: Apex Language Server crashes with Out of Memory error and severe system-wide performance degradation.  New laptop (2.7 GHz quad core, 8GB RAM, SSD), very large org (~800 Apex classes & triggers, >450 test classes).  Apex Language Server crashes (after 15 minutes) with the same Out of Memory issue.  However, the performance degradation on Windows 10 is so severe, the video and usb subsystems stop working (e.g. screen goes dark, mouse, keyboard don't function, other usb devices get disconnected) for about 5-10 minutes while 64-bit Javaw.exe consumes all available resources.  If more than one apex tab is open, then the server restarts itself (I'm guessing for each tab) and we go through it all over again.  So right now, while I wait for another 8GB of RAM to arrive, I am unable to use VS Code for Salesforce development.  

VS Code v1.35.1, Salesforce Extension Pack v46.2, Java 11, SFDX sfdx-cli/7.12.3-bfc421fa08 win32-x64 node-v10.15.3

**Comment by praksb** [comment]
Thanks for reporting the problem. We are working on this currently and will roll out incremental improvements to perf in the coming releases. I'll update this thread when we have some changes ready for you to try.

**Comment by ClemABT** [comment]
Thanks for the update and will let you know results of my tests.

**Comment by praksb** [comment]
We have made a perf improvement that would prevent OOM exception from happening when loading test methods. Please try and let us know if you still have issues. Also, please note that we still don't support indexing of larger orgs well and this fix doesn't address that.

**Comment by ClemABT** [comment]
I still get OOM exception when loading tests with the latest version, test panel is empty.

**Comment by praksb** [comment]
@ClemABT Can you confirm if the call stack is the same? Do you see  apex.jorje.lsp.impl.index.ApexIndex.getTestMethods(ApexIndex.java) in the call stack? It is also possible that indexing is failing because of the org size. Can you copy/paste the complete contents of the OUTPUT window?

**Comment by ClemABT** [comment]
You are right, it's not exactly the same call stack.
`GRAVE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by TwistyPop** [comment]
I don't understand why "large orgs" can't be supported. SalesForce is no longer supporting Force.com IDE and touting this as the go to plugin for VS Code. Not being able to support large orgs and Sales Force showing this plugin as the go to has got to be damaging?

**Comment by praksb** [comment]
@TwistyPop I am a Salesforce employee and work on the Apex extension. We are aware of the perf issue and has been incrementally rolling out fixes that would improve the experience for customers with huge number of Apex classes and triggers. #1430 is one such fix that would reduce the memory usage. We have work in our backlog to continue to make such improvements in the near future.

**Comment by matteobosc** [comment]
Hi, I have the same issue. Until few days ago it worked fine.

VS Code: 1.38.1
Salesforce CLI: 7.26.0-9118501918
Salesforce Extension Pack: 46.16.0
OS: Windows 10 Enterprise
Processor: Intel Core i7-8850H 2.60 GHz
RAM: 16GB

Apex Classes: 1312

Apex Language Server error:

`10:59:56.635 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
set 30, 2019 10:59:56 AM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 16 ms.
11:00:00.298 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
11:00:00.327 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
11:00:02.392 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
11:00:02.392 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 5831 ms.
set 30, 2019 11:06:01 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

Why this issue is closed?

**Comment by jitenderpadda** [comment]
I faced the same issue and the reason I believe it was happening was because I was using 32-bit Java which has a lower heap size. I installed 64-bit Java and pointed the Apex language server to use the 64-bit version in the vs code settings and that seems to have done the trick.

**Comment by ClemABT** [comment]
Thanks for the tips, it seems to work for the moment.

**Comment by TwistyPop** [comment]
@ClemABT what is the name of the setting you override, can you give an ex.?

**Comment by ClemABT** [comment]
@TwistyPop the setting I changed is salesforcedx-vscode-apex.java.home
I set it up to point to a 64-bits JRE located in C:\Program Files\Java\jre1.8.0_231
