### ISSUE TITLE
Apex language server could not provide information about valid breakpoints. 

### ISSUE THREAD

**Issue by gtiancai** [forcedotcom/salesforcedx-vscode#1496]
### Summary

_I'm trying to use Replay Debugger to debug targets a sandbox following this link: https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/replay-debugger

As it states below, I think it supports SANDBOX for now, right?

> Set Up an Apex Replay Debugger Session for a Sandbox or Production Org
> If you’re not using a scratch org or an org that you’ve set as your default org for development in VS Code, download a debug log from your org before you start debugging. Open that log in VS Code and then start a debugging session.
> 
> In VS Code, open the debug log that you want to analyze. Generate the log with a log level of FINER or FINEST for VISUALFORCE and a log level of FINEST for APEX_CODE.
> Run SFDX: Launch Apex Replay Debugger with Current File.
> TIP: If your log file is part of your Salesforce DX project, you don’t need to open the log file and then run a separate command. Instead, you can find a log file in the Explorer view, right-click it, and select Launch Apex Replay Debugger with Current File.

What I do:

1. use SFDX creates a project with manifest against my Sandbox org
2. create a checkpoint in Develop Console (sfdx:toggle checkpoint and sfdx:update checkpoints in Org do not work with errors)
3. Setup an log trace level (Apex Code: finest, Visualforce: finer) for one community user
4. login into community portal with above user, repro the issue
5. get correct log with SFDX:Get Apex Debug Logs
6. right click on the log file in VS Code and select 'SFDX: Launch Apex Replay Debugger with Current file'. The error pops up.

But debugging **works well** for my TrailHead playground org, which project is created with command 'SFDX: Create project' instead of 'SFDX: Create project with manifest', following checkpoint setup process from trailhead.

Any suggestions on this? Does Replay Debugger support Sandbox?
_.

**Comment by gtiancai** [comment]
Seems it works if create project with 'SFDX: Create project', but not for 'SFDX: Create project with Manifest' or manually add manifest. Why?

**Comment by DrewCPU** [comment]
Restarting VSCode helps sometimes for me but not always. Here is the error I'm getting from the Apex Language Server output:

`ERROR a.j.l.impl.debug.ApexDebuggerService - Error trying to get line breakpoint info
java.lang.IllegalStateException: Duplicate field: errorThrown
	at apex.common.base.Result.throwIfError(Result.java:112)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.create(VirtualFieldTableInitializer.java:103)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.get(VirtualFieldTableInitializer.java:94)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.get(VirtualFieldTableInitializer.java:38)
	at apex.common.base.Initializers$MemoizingInitializer.get(Initializers.java:74)
	at apex.jorje.semantic.symbol.type.AbstractTypeInfo.fields(AbstractTypeInfo.java:132)
	at apex.jorje.semantic.symbol.resolver.VariableResolver.lookup(VariableResolver.java:171)
	at apex.jorje.semantic.symbol.resolver.VariableResolver.lookup(VariableResolver.java:101)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupVariableInfo(StandardSymbolResolver.java:229)
	at apex.jorje.semantic.ast.expression.VariableExpression.validate(VariableExpression.java:95)
	at apex.jorje.semantic.ast.expression.AssignmentExpression.validate(AssignmentExpression.java:119)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.validate(ExpressionStatement.java:60)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.IfBlockStatement.validate(IfBlockStatement.java:62)
	at apex.jorje.semantic.ast.statement.IfElseBlockStatement.validate(IfElseBlockStatement.java:118)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.IfBlockStatement.validate(IfBlockStatement.java:62)
	at apex.jorje.semantic.ast.statement.IfElseBlockStatement.validate(IfElseBlockStatement.java:118)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.TryCatchFinallyBlockStatement.validate(TryCatchFinallyBlockStatement.java:101)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.IfElseBlockStatement.validate(IfElseBlockStatement.java:118)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.validate(MethodBlockStatement.java:82)
	at apex.jorje.semantic.ast.member.Method.validate(Method.java:172)
	at apex.jorje.semantic.ast.compilation.UserClass.validate(UserClass.java:183)
	at apex.jorje.semantic.compiler.CodeUnit.validate(CodeUnit.java:220)
	at apex.jorje.semantic.compiler.CompilerOperations$ValidateOperation.invoke(CompilerOperations.java:96)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processFirstStage(CompilerStageProcessor.java:134)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processToStage(CompilerStageProcessor.java:103)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:120)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:110)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:100)
	at apex.jorje.lsp.impl.debug.ApexDebuggerService.lambda$lineBreakpoints$0(ApexDebuggerService.java:91)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.debug.ApexDebuggerService.lineBreakpoints(ApexDebuggerService.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Everything else appears to be working properly.

**Comment by rklemm** [comment]
@KevSlashNull  - Thank you so much for following up with that!! That was also my issue as well. I have been trying to solve this off and on for MONTHS, and just hit an issue yesterday that I am really struggling with where adding debug statements was just not going to cut it. I cannot believe the timing of your post - you just saved my weekend!!

**Comment by randi274** [comment]
Hi @gtiancai are you still encountering the issue with the replay debugger in sandboxes?

**Comment by zerkz** [comment]
I got hit with this same issue ( two fields static and non-static, API version 46), but I am not able to refactor the erroneous code without code review/etc. I am going to look for a way to tell the apex language server to avoid the erroneous apex classes if possible.

**Comment by LiveLikeLastDay** [comment]
> Seems it works if create project with 'SFDX: Create project', but not for 'SFDX: Create project with Manifest' 
Same here.

**Comment by WyrnCael** [comment]
In my case the problem was in the sfdx-project.json file. The name and namespace were reversed. It had the following format:

    {
      "packageDirectories": [
          {
              "path": "force-app",
              "default": true
          }
      ],
      "name": "",
      "namespace": "project-name",
      "sfdcLoginUrl": "https://login.salesforce.com",
      "sourceApiVersion": "55.0"
    }

Putting the name and namespace correctly solved the problem:

    {
      "packageDirectories": [
          {
              "path": "force-app",
              "default": true
          }
      ],
      "name": "project-name",
      "namespace": "",
      "sfdcLoginUrl": "https://login.salesforce.com",
      "sourceApiVersion": "55.0"
    }

I hope it can help someone, best regards.

**Comment by stafik** [comment]
Thanks a lot @KevSlashNull! I'm having precisely the same issue.
I didn't know how to check Apex Language Server output at the beginning so for anyone looking it, it's here in VS Code:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/21193669/76d56ac6-0a8c-4e88-922a-fc1b2c0434ec)

I took a step further and checked that having two class variables (static and non-static) seems to work in Apex:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/21193669/8dd064fe-91fe-4571-ad38-2f71183e5caa)
However it should not be possible in Java - https://stackoverflow.com/questions/26222844/may-static-and-non-static-variables-have-the-same-name and I guess that's why I got the error in Apex Replay Debugger.

**Comment by supert3d** [comment]
Hey all, I recently updated the Salesforce CLI (Windows 11) and I've started getting the same error: "Apex Language Server could not provide information about valid breakpoints." - unfortunately though there's no output in the terminal from Apex Language Server. 

I've checked/updated the following: 

- Salesforce Extensions
- VSCode
- JAVA (checked JAVA HOME is set etc... in PATH)
- Salesforce CLI

**Comment by supert3d** [comment]
To anyone following this thread, this helped me. 

> To clear the Apex Language Server’s indexing, delete the `PROJECT_DIR/.sfdx/tools/<Salesforce Release>` directory and restart VS Code.

https://developer.salesforce.com/tools/vscode/en/apex/language-server#reset-apex-indexing

**Comment by mattlacey** [comment]
Additional info - the `<Salesforce Release>` directory will be a number, I hit this scenario today and it was `246`.
