### ISSUE TITLE
Unhandled exception running Apex test with only `@TestSetup` method

### ISSUE THREAD

**Issue by rogeramitchell** [forcedotcom/salesforcedx-vscode#1507]
### Summary

- Before writing a test method (`@isTest` annotated method), it's helpful to ensure that any data that will be used as basis for test will successfully insert within the setup (`@TestSetup` method)
- VS Code (and likely `sfdx`) throws an exception running an Apex test that only contains a `@TestSetup` method
- Developer Console (and other IDEs) successfully handle the result of running an Apex test that only contains a `@TestSetup` method

### Steps To Reproduce:

1.  Create an Apex test class `MyTest` (see example code below)
1.  Run the Apex test class by either using `Run All Tests` link that appears beneath `@isTest` annotation in the class, or `SFDX: Invoke Apex Tests...` from command palette and select `MyTest`

```apex
@isTest
public class MyTest 
{
    @TestSetup
    static void testSetup()
    {
        Account thing = new Account();
        thing.Name = 'Test';
        insert thing;
    }
}
```

### Expected result

- Output provides context about whether success or error occurred with `@TestSetup` method
- Output does not produce an `Unhandled rejection Error`
- Developer Console (in Salesforce) shows that test ran successfully

### Actual result

- Output provides an exception (see full details below in Additional information)
- Developer Console (in Salesforce) shows that test ran successfully

### Additional information

**Output in VS Code**

```
Starting SFDX: Invoke Apex Tests...

14:40:13.877 sfdx force:apex:test:run --classnames MyTest --resultformat human --outputdir /Users/rogermitchell/Desktop/my-sfdx-project/.sfdx/tools/testresults/apex --loglevel error
Unhandled rejection Error: No test results found
    at new TestResults (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/test/testResults.js:19:19)
    at new ApexTestResults (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/apex/apexTestApi.js:175:9)
    at org.getConfig.then.then.then.results (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/apex/apexTestApi.js:795:32)
    at tryCatcher (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/rogermitchell/.local/share/sfdx/client/node_modules/salesforce-alm/node_modules/bluebird/js/release/promise.js:431:57)
ERROR running force:apex:test:run:  Cannot read property 'message' of undefined
14:40:18.364 sfdx force:apex:test:run --classnames MyTest --resultformat human --outputdir /Users/rogermitchell/Desktop/my-sfdx-project/.sfdx/tools/testresults/apex --loglevel error ended with exit code 1
```

**VS Code Version**: Version 1.36.1 (1.36.1)

**SFDX CLI Version**: sfdx-cli/7.1.4-79f97a7df8 darwin-x64 node-v10.15.3

**OS and version**: macOS 10.14.5 (18F203)

**Comment by LeviLong01** [comment]
I'm assuming the reason this happens is because you did not run "SFDX: Deploy Source to Org" first and then run "Run Test"/"Run All Tests" etc....

I went in to the Developer Console and noticed my test class did not exist in the Org as I never pushed it.

So I ran "SFDX: Deploy Source to Org" from VS and then opened Developer Console and ran my test. All was successful.

Then I went to VS and clicked "Run All Tests", this time being successful without the error received above.

**Solution Summary:**
Run "SFDX: Deploy Source to Org" on the test class and then run your test in VS
