### ISSUE TITLE
Excessive CPU, Memory, and Energy Use When Salesforce Extension Pack is Enabled

### ISSUE THREAD

**Issue by jeramy-dichiera** [forcedotcom/salesforcedx-vscode#1592]
### Summary

When the Salesforce Extension Pack is enabled I am experiencing greatly increased CPU, memory, and energy use. Currently Visual Studio Code 'Code Helper' is using 214% CPU, 303 energy impact, and 1.86 GB memory.

Please let me know if there is any specific information I can supply.

### Steps To Reproduce:

1.  Open a code base in Visual Studio Code with Salesforce Extension Pack enabled.
1.  Open Activity Monitor
 - Note that Visual Studio Code Code Helper is using excessive resources.

### Expected result

When using the Salesforce Extension Pack, Visual Studio Code consumes less resources and can be used on battery power.

### Actual result

When using the Visual Studio Code Extension Pack, Visual Studio Code appears to use excessive resources and needs to be disabled in order to retain battery life.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**SFDX CLI Version**:
`sfdx-cli/7.20.1-d88ae4707c darwin-x64 node-v10.15.3
`

**OS and version**:
`macOS Mojave 10.14.6`

**Comment by adityababbar** [comment]
This happens for me only when Indexing of Lightning Components occurs. On then my CPU utilization is 100% and PC is useless. It seems this indexing is CPU hog.

![image](https://user-images.githubusercontent.com/4994304/64381888-405f2500-d002-11e9-9672-2e42c0206452.png)

**Comment by arneper** [comment]
I also seem to be caught in the endless Indexing Lightning Components cycle. What information would be helpful fro me to provide? Thanks

**Comment by rapsacnz** [comment]
Here is a sample of the error output I get:

`
(node:2897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 6:48:55 AM] (node:2897) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (/Users/caspar/.vscode/extensions/salesforce.salesforcedx-vscode-lightning-47.9.0/node_modules/lwc-language-server/lib/metadata-utils/static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (/Users/caspar/.vscode/extensions/salesforce.salesforcedx-vscode-lightning-47.9.0/node_modules/aura-language-server/lib/server.js:39:9)
[Error - 6:48:55 AM] (node:2897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 6:48:55 AM] (node:2897) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by victorng8** [comment]
I also got @rapsacnz 's error. 
I also can no longer retrieve/deploy from/to target org.

<img width="888" alt="deployToSourceMissing" src="https://user-images.githubusercontent.com/1401896/70597550-9a840d80-1c23-11ea-9b3d-adf396df052d.png">

**Comment by pogilvie** [comment]
Me too.   I've had the spinning 'Indexing Lightning Compoents' issue.  I disabled the Aura component extension and it stoped.

**Comment by ralphcallaway** [comment]
Ditto, I can hardly type vs code gets so slow with the Aura component extension on.

**Comment by danielenriquez** [comment]
Same problem with "Indexing Lightning Components"
Give me this errors when VSC start:
Error queuing up indexing of static resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of content resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexContentAssets (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\content-assets-util.js:56:83)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of labels. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexCustomLabels (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\custom-labels-util.js:51:82)
    at async Promise.all (index 4)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:17352) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:17352) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:17352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Loading support library: browser
Loading support library: ecmascript
[Info  - 14:01:53] ... language server started in 769.02 ms
Error queuing up indexing of static resources. Error details:
Error queuing up indexing of content resources. Error details:
Error queuing up indexing of labels. Error details:
[Error - 14:01:53] (node:17352) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 14:01:53] (node:17352) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\user.name\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 14:01:53] (node:17352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 14:01:53] (node:17352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 14:01:53] (node:17352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 14:01:53] (node:17352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Indexed 11 files in 1627.75 ms ms
[Info  - 14:01:55] Indexed 11 files in 1627.75 ms ms
loadCustomTagsFromFiles: processed 16 files in 610.98 ms
loadCustomTagsFromFiles: processed 16 files in 610.98 ms
[Info  - 14:01:59] aura onDidChangeWatchedFiles...
aura onDidChangeWatchedFiles...

**Comment by q-jack** [comment]
same problem here as well

**Comment by stoevie** [comment]
since the beginning of this week I also have the same problem as danielenriquez.

**Comment by juliolima86** [comment]
> This happens for me only when Indexing of Lightning Components occurs by Aura Component Extension. Only then my CPU utilization is 100% and PC is useless. It seems this indexing is a CPU hog.
> 
> ![image](https://user-images.githubusercontent.com/4994304/64381888-405f2500-d002-11e9-9672-2e42c0206452.png)

+1

**Comment by danielenriquez** [comment]
Hi guys, VSC today's update fix the bug :)
![Annotation 2019-12-13 090749](https://user-images.githubusercontent.com/8003697/70782830-2e6eea00-1d88-11ea-8d68-fb6919359ccb.png)

**Comment by AlejandroGil29** [comment]
Currently I,m having the same issue 'Indexing Lightning components' is taking to long to load and I have the newest version of Visual Studio Code:
![VSCodeVersion](https://user-images.githubusercontent.com/34262672/84917441-f45b0980-b084-11ea-8552-bf341ad68372.jpg)

Any suggestions?

**Comment by smaddox-sf** [comment]
Duplicate #2050
