### ISSUE TITLE
Java heap space error caused by ApexIndexer

### ISSUE THREAD

**Issue by pibenett** [forcedotcom/salesforcedx-vscode#1626]
Hello,

Unfortunately the same issue as #1103 is still exiting. I'm unable to load the @isTest panel and the code completion is not working.
Here is the complete log generated when I tried to run a test from VSCode for example:

`10:16:27.791 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
10:16:27.800 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
10:16:29.740 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 7367 ms.
10:16:29.744 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
sept. 03, 2019 10:18:07 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
GRAVE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by jgrimaldos** [comment]
Same scenario as in #1581 but no one seems to be taking a look into it, there's a big issue regarding memory handling with big orgs. In the current state, this tool is not viable as a development enviroment.

**Comment by AntunBartonicek** [comment]
Experiencing the same issue. It not only eats-up all CPU (for like 20 minutes) and memory during startup it also makes plugin almost useless.
Can we at least turn it off until large orgs are supported as right now there is no use for this indexer.

**Comment by stohn777** [comment]
@ntotten 
Carrying over from the SF Success Community question.  The error above is somewhat similar to the ones that we get when opening org that have a very large number of metadata artifacts.

From yesterday when I re-opened a massive-org project ...
`12:36:54.324 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Nov 07, 2019 12:36:55 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 9 ms.
12:36:59.076 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
12:36:59.084 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
12:37:00.545 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
12:37:00.548 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 6223 ms.
Exception in thread "ForkJoinPool.commonPool-worker-27" java.lang.OutOfMemoryError: Java heap space`

**Comment by stohn777** [comment]
@ntotten
Today when I opened one of my very massive orgs, the Apex Language Server failed with the typical 'Java heap space' exception.  Attached is the whole log.  Please let me know if you'd like more information when this situation occurs.

[ApexLanguageServerLog-AfterJavaHeapSpaceException.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/3848592/ApexLanguageServerLog-AfterJavaHeapSpaceException.txt)

**Comment by lcampos** [comment]
Hi, in release `47.15.0` we added a change that allows you to configure the memory allocated to the Apex language server process which might help when working with large Apex projects. Here are the docs on it https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup

**Comment by smaddox-sf** [comment]
As noted above, we released a way that you can add more memory.  No further work planned on this at this time, so closing this.

**Comment by AntunBartonicek** [comment]
Adding more memory is not a fix as it simply delays the problem. No matter how much memory we assign this error WILL happen.
Should we start using servers with TB of RAM in order to use apex indexer?

**Comment by smaddox-sf** [comment]
Hi @AntunBartonicek - You're right that more memory isn't a silver bullet and it doesn't help in all cases.  We are still seeing issues when indexing large projects and are tracking on #2410

**Comment by AntunBartonicek** [comment]
> 
> 
> Hi @AntunBartonicek - You're right that more memory isn't a silver bullet and it doesn't help in all cases. We are still seeing issues when indexing large projects and are tracking on #2410

Thanks...
