### ISSUE TITLE
salesforce.salesforcedx-vscode-apex not activating on fresh install

### ISSUE THREAD

**Issue by tagCincy** [forcedotcom/salesforcedx-vscode#1659]
### Summary

Attempting to install extension on new MacBook Pro.  After installation, only "Open Lightning Component" command is available in Command Palette. Apex language server running as well.

### Steps To Reproduce:

1.  Install new instance of VSCode application
1.  Install salesforce-vscode extension
1. Open Command Palette and enter `sfdx`

### Expected result

Should see all available sfdx commands.

### Actual result

Only `SFDX: Open Lightning Component` showing.

### Additional information

Error from Dev Tool console showing salesforcedx-vscode-apex not activating properly:

```
Activating extension `salesforce.salesforcedx-vscode-apex` failed:  Class extends value undefined is not a constructor or null

TypeError: Class extends value undefined is not a constructor or null
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/commands/forceApexTestRunCodeAction.js:29:50)
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/commands/forceApexTestRunCodeAction.js:150:3)
	at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:840)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:588)
	at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.t.getExtensionPathIndex.then.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:615)
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/commands/index.js:9:36)
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/commands/index.js:19:3)
	at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:840)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:588)
	at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.t.getExtensionPathIndex.then.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:615)
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/index.js:22:20)
	at Object.<anonymous> (/Users/tagcincy/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.14.0/out/src/index.js:166:3)
	at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:840)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:588)
	at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
	at Function.t.getExtensionPathIndex.then.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:32:381)
	at f._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:632)
	at f._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:27)
	at f._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:108)
	at f.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:937)
	at Generator.next (<anonymous>)
	at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:83)
	at new Promise (<anonymous>)
	at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:862)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:639)
	at p._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:21)
	at define._activateExtensions.r.length.Promise.all.s.map.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:628)
	at Array.map (<anonymous>)
	at p._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:616)
	at define._activateExtensions.r.length._activateExtensions.then.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:713)

```
**VS Code Version**:  1.38.1

**SFDX CLI Version**: 1.38.1

**OS and version**: Darwin x64 18.2.0 (macOS Mojave)

**Comment by tagCincy** [comment]
I figured this out; `salesforcedx-vscode-core.internal-development` was enabled.
