### ISSUE TITLE
Cannot find module 'shelljs'

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/salesforcedx-vscode#1756]
### Summary

For whatever reason, I'm not able to use sfdx extensions anymore in vscode.
Looking at the console logs, I'm seeing the following error:
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243 [Extension Host] Activating extension `salesforce.salesforcedx-vscode-core` failed:  Cannot find module 'shelljs'
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243
```
I tried to reinstall everything, and to install previous versions, but it still doesn't work so it's likely something with my local setup, but don't know what it could be. Opening an issue in case I'm not the only one or to see if anyone have an idea of what the reason could be.

### Steps To Reproduce:

Either easy or hard to reproduce: I've just installed everything (vscode + CLI + extensions) to the latest version, and extensions are crashing at launch.

### Expected result

Extensions are launched when vscode starts.

### Actual result

Extensions are crashing.

### Additional information

Full stack:
````
[Extension Host] Activating extension `salesforce.salesforcedx-vscode-core` failed:  Cannot find module 'shelljs'
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243 [Extension Host] Here is the error stack:  Error: Cannot find module 'shelljs'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
	at Function.Module._load (internal/modules/cjs/loader.js:510:25)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/util/cliConfiguration.js:9:19)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/util/cliConfiguration.js:36:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/util/index.js:15:26)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/util/index.js:23:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/commands/forceApexExecute.js:22:16)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/commands/forceApexExecute.js:82:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/commands/index.js:9:26)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/commands/index.js:94:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/index.js:19:20)
	at Object.<anonymous> (/Users/fabientaillon/.vscode/extensions/salesforce.salesforcedx-vscode-core-47.2.0/out/src/index.js:231:3)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:32:963)
	at t.ExtHostExtensionService._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:755:484)
	at t.ExtHostExtensionService._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:300)
	at t.ExtHostExtensionService._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:665:360)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:296)
	at t.ExtensionsActivator._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:731)
	at n.length.Promise.all.r.map.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:409)
	at Array.map (<anonymous>)
	at t.ExtensionsActivator._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:397)
	at t.ExtensionsActivator._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:466)
	at t.ExtensionsActivator.activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:422)
	at t.ExtHostExtensionService._activateById (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:664:87)
	at t.ExtHostExtensionService._activateIfFileName (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:669:100)

**Comment by FabienTaillon** [comment]
With 47.3 it's working again. Not sure what was the issue but it's fine now.

**Comment by bailey293** [comment]
For what it's worth, I ran into this on my machine recently as well. I had to delete the extension folders and reinstall the extensions. This happened around the time VSCode had an update.
