### ISSUE TITLE
ERROR a.j.l.i.c.CodeActionsProviderAggregator - Encountered an error with code action provider apex.jorje.lsp.impl.codeActions.ApexCodeActionsProvider@64e7619d java.lang.IllegalStateException: Method already defined:

### ISSUE THREAD

**Issue by pauljuneau** [forcedotcom/salesforcedx-vscode#1812]
### Summary

This error is continuously popping up in my output panel while working on a class that can compile and deploy just fine: ERROR a.j.l.i.c.CodeActionsProviderAggregator - Encountered an error with code action provider apex.jorje.lsp.impl.codeActions.ApexCodeActionsProvider@64e7619d java.lang.IllegalStateException: Method already defined:

### Steps To Reproduce:

1.  Unsure

### Expected result

Output panel should not popup with exceptions continuously.

### Actual result

Output panel is continuously popping up with this error.

### Additional information
09:07:22.244 [ForkJoinPool.commonPool-worker-2] ERROR a.j.l.i.c.CodeActionsProviderAggregator - Encountered an error with code action provider apex.jorje.lsp.impl.codeActions.quickFix.DeclareMissingMethodProvider@723e88f9
java.lang.IllegalStateException: Method already defined: _someMethod_ void ClassName.someMethod(param) from the type ClassName
	at apex.common.base.Result.throwIfError(Result.java:112)
	at apex.jorje.semantic.symbol.member.method.MethodTableFactory.newMethodTable(MethodTableFactory.java:44)
	at apex.jorje.semantic.symbol.member.method.MethodTableFactory.newMethodTable(MethodTableFactory.java:39)
	at apex.jorje.lsp.impl.index.symbol.VirtualMethodTableInitializer.get(VirtualMethodTableInitializer.java:74)
	at apex.jorje.lsp.impl.index.symbol.VirtualMethodTableInitializer.get(VirtualMethodTableInitializer.java:40)
	at apex.common.base.Initializers$MemoizingInitializer.get(Initializers.java:74)
	at apex.jorje.semantic.symbol.type.AbstractTypeInfo.methods(AbstractTypeInfo.java:122)
	at apex.jorje.semantic.symbol.resolver.MethodResolver.lookup(MethodResolver.java:74)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupMethodInfo(StandardSymbolResolver.java:218)
	at apex.jorje.semantic.ast.expression.NewObjectExpression$1._default(NewObjectExpression.java:150)
	at apex.jorje.semantic.ast.expression.NewObjectExpression$1._default(NewObjectExpression.java:133)
	at apex.jorje.semantic.symbol.type.visitor.TypeInfoVisitor$Default.visit(TypeInfoVisitor.java:56)
	at apex.jorje.lsp.impl.index.symbol.VirtualStandardTypeInfo.accept(VirtualStandardTypeInfo.java:84)
	at apex.jorje.semantic.ast.expression.NewObjectExpression.validate(NewObjectExpression.java:132)
	at apex.jorje.semantic.ast.expression.AssignmentExpression.validate(AssignmentExpression.java:118)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.validate(ExpressionStatement.java:60)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.validate(MethodBlockStatement.java:82)
	at apex.jorje.semantic.ast.member.Method.validate(Method.java:172)
	at apex.jorje.semantic.ast.compilation.UserClass.validate(UserClass.java:183)
	at apex.jorje.semantic.compiler.CodeUnit.validate(CodeUnit.java:220)
	at apex.jorje.semantic.compiler.CompilerOperations$ValidateOperation.invoke(CompilerOperations.java:96)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processFirstStage(CompilerStageProcessor.java:134)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processToStage(CompilerStageProcessor.java:103)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:120)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:110)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:159)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:90)
	at apex.jorje.lsp.impl.codeActions.BaseCodeActionsProvider.compileAndTraverse(BaseCodeActionsProvider.java:90)
	at apex.jorje.lsp.impl.codeActions.quickFix.DeclareMissingMethodProvider.getCodeActions(DeclareMissingMethodProvider.java:78)
	at apex.jorje.lsp.impl.codeActions.BaseCodeActionsProvider.lambda$provideCodeActions$0(BaseCodeActionsProvider.java:79)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.codeActions.BaseCodeActionsProvider.provideCodeActions(BaseCodeActionsProvider.java:77)
	at apex.jorje.lsp.impl.codeActions.CodeActionsProviderAggregator.lambda$provideCodeActions$0(CodeActionsProviderAggregator.java:59)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeActions.CodeActionsProviderAggregator.provideCodeActions(CodeActionsProviderAggregator.java:57)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeAction$7(StandardTextDocumentService.java:291)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**VS Code Version**: 
Version 1.33.1 (1.33.1)

**SFDX CLI Version**:
sfdx-cli/7.30.13-9e204762d5 darwin-x64 node-v10.15.3

**OS and version**:
macOS Mojave
Version 1014.6

**Comment by AndrewRayCode** [comment]
I got this too repeatedly on a class that could deploy fine. No idea what caused it, but it went away on its own

> java.lang.IllegalStateException: Method already defined: getName String

**Comment by AnanyaJha** [comment]
Hi @pauljuneau thanks for reporting this! I have not been able to repro this issue locally; is there any other information you can provide? Is it occurring on a specific file you have? And what version of the extensions are you currently using?
