### ISSUE TITLE
Indexing Lightning Components is stuck forever

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#1832]
After updating to latest release 47.9.0 every time I open VScode the output window pops up automatically showing a lot of errors under 'Aura Language Server' and 'indexing lightning components' in the status bar below goes on forever. This should be affecting all users, can you please prioritize this?

![image](https://user-images.githubusercontent.com/19307757/70422124-7ed60700-1a6b-11ea-9f21-f13666185194.png)

This is the content of the output window

`Starting *AURA* language server at c:\Users\ChakrabortyS\VSCode Projects\Verivox dev
[Info  - 09:59:16] Starting *AURA* language server at c:\Users\ChakrabortyS\VSCode Projects\Verivox dev
Loading support library: browser
Loading support library: browser
Loading support library: ecmascript
... language server started in 1116.33 ms
Loading support library: ecmascript
[Info  - 09:59:17] ... language server started in 1116.33 ms
Error queuing up indexing of static resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of content resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexContentAssets (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\content-assets-util.js:56:83)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of labels. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexCustomLabels (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\custom-labels-util.js:51:82)
    at async Promise.all (index 4)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:9528) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:9528) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:9528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error queuing up indexing of static resources. Error details:
Error queuing up indexing of content resources. Error details:
Error queuing up indexing of labels. Error details:
[Error - 09:59:17] (node:9528) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 09:59:17] (node:9528) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\ChakrabortyS\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 09:59:17] (node:9528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 09:59:17] (node:9528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 09:59:17] (node:9528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 09:59:17] (node:9528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
loadCustomTagsFromFiles: processed 2 files in 210.99 ms
loadCustomTagsFromFiles: processed 2 files in 210.99 ms
Indexed 15 files in 1412.83 ms ms
[Info  - 09:59:18] Indexed 15 files in 1412.83 ms ms
`

**Comment by Arkin69** [comment]
Same issue with same error

**Comment by steals** [comment]
The same issue reported on September https://github.com/forcedotcom/salesforcedx-vscode/issues/1684

**Comment by sc5148** [comment]
@steals I don't think they are the same issues but similar, yes. This started happening just after updating to the latest version i.e. 47.9.0

**Comment by kvan** [comment]
Also only started with 47.9.0 for me. They may be related but some new change must have expanded the number of states in which this can occur.

**Comment by BenRussert** [comment]
Are all of us with the issue on windows?

**Comment by jdotpo** [comment]
I'm on macOS Mojave (10.14.6) and seeing the same issue

**Comment by ntotten** [comment]
We are investigating and will get a fix out asap.

**Comment by alechko** [comment]
Having this issue as well on debian linux, vscode 1.40.2, Salesforce Extension Pack 47.9.0

**Comment by paulo-ps84** [comment]
Having this issue as well on Ubuntu 19.10, vscode 1.40.2, Salesforce Extension Pack 47.9.0

**Comment by victorng8** [comment]
I have the same issue and **MORE** (can't even create a project or do SFDX: Retrieve from source org)
I opened an issue here https://github.com/forcedotcom/salesforcedx-vscode/issues/1840

**Comment by jwnelson2019** [comment]
Also experiencing this issue.

**Comment by amy-herz** [comment]
same issue here as well
Windows 10 v1803, sfdx 47.9.2, vscode 1.40.2

**Comment by NathanWenslaff** [comment]
This issue is affecting me on macOS Sierra Version 10.12.6.

The process hogs CPU resources and makes VSCode sluggish.

**Comment by sc5148** [comment]
@ntotten Any ETA for this one?

**Comment by BenRussert** [comment]
> Any ETA for this one?

I think this is the same issue and @nrkruk says 47.10 should be released today:
https://github.com/forcedotcom/salesforcedx-vscode/issues/1840#issuecomment-564686814

**Comment by AnanyaJha** [comment]
This should be addressed with our latest release (47.10.0).

**Comment by AlejandroGil29** [comment]
I have the same issue with version 1.46.0 :(
