### ISSUE TITLE
Starting client failed: Couldn't start client Aura Language Server 

### ISSUE THREAD

**Issue by neelgo** [forcedotcom/salesforcedx-vscode#1839]
- VSCode Version: 1.40.2
- OS Version: windows 10

Steps to Reproduce:
I am using it for salesforce development and install salesforce extension pack
I am getting error from Aura Language server
[Error - 11:36:05 AM] Starting client failed
Error: spawn C:\Users\.....\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

*Tried reinstalling extension it failed shows same error
and reinstalled vscode also still same.
* Not sure but it is happening after last update. how I can go back to last version?

Does this issue occur when all extensions are disabled?: Yes/No
* Not sure how to do that and also I have to use it with extenstion for salesforce development
if it works without them still it is not useful.

![image](https://user-images.githubusercontent.com/9036100/70596788-c051e800-1c0c-11ea-95ac-05b5bf671432.png)

**Comment by FabienTaillon** [comment]
I'm getting errors too, not sure this is the same problem:

<img width="1307" alt="aura" src="https://user-images.githubusercontent.com/2465122/70608917-3d776000-1c01-11ea-85d6-a6c693c487d3.png">

**Comment by nrkruk** [comment]
Fix will be released tomorrow

**Comment by AnanyaJha** [comment]
This should be addressed with our latest release (47.10.0).

**Comment by neelgo** [comment]
Updated it,  Still problem persists for me.

**Comment by neelgo** [comment]
I also tried to disable "Aura Components"
then there was not error but once enabled or updated or installed older version of extension
below error is there:
[Error - 10:06:39 AM] Starting client failed
Error: spawn C:\Users\Myusername\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by AnanyaJha** [comment]
@neelgo Just to confirm I'm understanding correctly, you're still seeing the "Indexing Lightning Components" message with the latest version of the extensions (47.10.0)?

**Comment by neelgo** [comment]
I am seeing the same message that i have posted 3 days before  and with initial question.
[Error - 10:06:39 AM] Starting client failed
Error: spawn C:\Users\Myusername\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)

not the one that you said.

**Comment by ptorreswenance** [comment]
Same problem all day. First time trying to use VSCode with SFDX 

```
[Error - 16:29:56] Starting client failed
Error: spawn C:\Users\pablo.torres\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by billiedd** [comment]
I updated to most recent version 47.17.1 and received this error. I tried the above troubleshooting steps of downgrading and uninstalling extension to no avail. 

Any help would be greatly appreciated, thanks in advance. 

`[Error - 4:10:42 PM] Starting client failed
Error: spawn C:\Users\Myusername\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)`

**Comment by psmmsp** [comment]
I am getting the same error. Error below any resolutions on this.

[Error - 11:22:26 pm] Starting client failed
Error: spawn C:\Users\prade\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by psmmsp** [comment]
I am getting the same error. Error below any resolutions on this.

[Error - 11:22:26 pm] Starting client failed
Error: spawn C:\Users\psm\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by evaldes** [comment]
Also getting the same error

[Error - 10:48:31 AM] Starting client failed
Error: spawn C:\Program Files\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
