### ISSUE TITLE
SFDX (Version 47.9.0) functionality totally cannot work on Windows

### ISSUE THREAD

**Issue by victorng8** [forcedotcom/salesforcedx-vscode#1840]
### Summary

_During these past 2 months, I was able to access all functionalities and deploy/retrieve code to/from Salesforce source orgs. Suddenly, when I open up visual studio code everything is suddenly not working_.

### Steps To Reproduce:

1.  Open up existing Salesforce project using VS Code
2.  Aura Language Server error encountered
3.  Bottom left screen is forever "Indexing Lightning Components"
4.  Cannot perform from Command Palette "SFDX: Create Project with Manifest" etc
5.  Right Click existing Salesforce project under Manifest -> Package.xml no longer have "SFDX: Retrieve from Source Org"

### Expected result

1.  No errors encountered
3.  Bottom left screen should show my username of source org it is authorized in
4.  Able to perform from Command Palette "SFDX: Create Project with Manifest" etc
5.  Able to Right Click existing Salesforce project under Manifest -> Package.xml to "SFDX: Retrieve from Source Org"

### Actual result

1.  Aura Language Server error encountered
2.  Bottom left screen is forever "Indexing Lightning Components"
3.  Cannot perform from Command Palette "SFDX: Create Project with Manifest" etc "command 'sfdx.force.project.with.manifest.create' not found"
4.  Right Click existing Salesforce project under Manifest -> Package.xml no longer have "SFDX: Retrieve from Source Org"

### Additional information

> [Info  - 4:57:17 pm] Starting *AURA* language server at c:\Users\<USER>\SFDC_Workspace\lightning17032019--uat
Starting *AURA* language server at c:\Users\<USER>\SFDC_Workspace\lightning17032019--uat
Loading support library: browser
Loading support library: browser
Loading support library: ecmascript
... language server started in 578.18 ms
Loading support library: ecmascript
[Info  - 4:57:17 pm] ... language server started in 578.18 ms
Error queuing up indexing of static resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of content resources. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexContentAssets (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\content-assets-util.js:56:83)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
Error queuing up indexing of labels. Error details: TypeError: Cannot read property '0' of undefined
    at Object.indexCustomLabels (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\custom-labels-util.js:51:82)
    at async Promise.all (index 4)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:10092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:10092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
(node:10092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error queuing up indexing of static resources. Error details:
Error queuing up indexing of content resources. Error details:
Error queuing up indexing of labels. Error details:
[Error - 4:57:17 pm] (node:10092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 4:57:17 pm] (node:10092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.indexStaticResources (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Timeout._onTimeout (c:\Users\<USER>\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)
[Error - 4:57:17 pm] (node:10092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 4:57:18 pm] (node:10092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 4:57:18 pm] (node:10092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 4:57:18 pm] (node:10092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Indexed 43 files in 1228.76 ms ms
[Info  - 4:57:19 pm] Indexed 43 files in 1228.76 ms ms
loadCustomTagsFromFiles: processed 34 files in 983.77 ms
loadCustomTagsFromFiles: processed 34 files in 983.77 ms

![Screenshot_1](https://user-images.githubusercontent.com/1401896/70607375-4b48d780-1c39-11ea-96f5-c3e19f676668.png)

### Versions
- Version: 1.40.2 (user setup)
- Date: 2019-11-25T14:54:45.096Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18362
- SFDX CLI Version: 47.9.0

**Comment by victorng8** [comment]
For anyone with same issue. A workaround is downgrading both extensions:

- Salesforce CLI Integration
- Salesforce Extension Pack

to version 47.6.0 

<img width="426" alt="47 6 0" src="https://user-images.githubusercontent.com/1401896/70608730-8fd57280-1c3b-11ea-9d9f-bcffd593b43b.png">

Note : Indexing Lightning Components will still be there forever but at least all the other issues I mentioned is working now

**Comment by nrkruk** [comment]
Fix will be released tomorrow

**Comment by dev-mks** [comment]
> For anyone with same issue. A workaround is downgrading both extensions:
> 
> * Salesforce CLI Integration
> * Salesforce Extension Pack
> 
> to version 47.6.0
> 
> <img alt="47 6 0" width="426" src="https://user-images.githubusercontent.com/1401896/70608730-8fd57280-1c3b-11ea-9d9f-bcffd593b43b.png">
> 
> Note : Indexing Lightning Components will still be there forever but at least all the other issues I mentioned is working now

How can we downgrade the version?

**Comment by brpowell** [comment]
@victorng8 Are you still seeing this with the latest? (47.10.0)

**Comment by victorng8** [comment]
Looks like all my issues are fixed now! Thank you Lightning Team!

Aura Language Server now says:

> Starting *AURA* language server at c:\Users\<user>\SFDC_Workspace\lightning17032019--uat
> Loading support library: browser
> Loading support library: ecmascript
> ... language server started in 797.65 ms
> Indexed 43 files in 2273.77 ms ms
> loadCustomTagsFromFiles: processed 34 files in 1257.12 ms
> [Info  - 9:25:33 am] Starting *AURA* language server at c:\Users\<user>\SFDC_Workspace\lightning17032019--uat
> Loading support library: browser
> Loading support library: ecmascript
> [Info  - 9:25:33 am] ... language server started in 797.65 ms
> [Info  - 9:25:34 am] Indexed 43 files in 2273.77 ms ms
> loadCustomTagsFromFiles: processed 34 files in 1257.12 ms
> [Info  - 9:25:41 am] aura onDidChangeWatchedFiles...
> aura onDidChangeWatchedFiles...
