### ISSUE TITLE
Not able to open the local Development server from vscode 

### ISSUE THREAD

**Issue by dsureshkumar4-github** [forcedotcom/salesforcedx-vscode#1868]
![Screen Shot 2020-01-13 at 7 25 49 PM](https://user-images.githubusercontent.com/59246508/72261297-8e340b80-363a-11ea-8c61-557e98513732.png)
Hi,

When I try to open the local development server in the VSCode then I am receiving the following error.  Please help me regarding this issue

{ Error: listen EADDRINUSE: address already in use :::3333
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Function.listen (/Users/sureshkumar/.local/share/sfdx/node_modules/express/lib/application.js:618:24)
    at Object.startServer (/Users/sureshkumar/.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/dist/server/talonServerCopy.js:74:46)
    at LocalDevServer.start (/Users/sureshkumar/.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/dist/server/LocalDevServer.js:126:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3333 }

**Comment by dsureshkumar4-github** [comment]
Resolved the issue by killing the process on port 3333 and restarted the VScode

Please go through the below link for how to kill the process

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_troubleshoot_cancel_auth.htm
