### ISSUE TITLE
Error: Cannot find module 'yeoman-generator'

### ISSUE THREAD

**Issue by gvadityagit** [forcedotcom/salesforcedx-vscode#1878]
### Summary

After installing Latest version Latest version of salesforce extension Pack , unable to create Project

### Steps To Reproduce:

1.  Install latest version of Salesforce extension Pack 
2.  Type Cntrl+Shift+P : Create Project from Manifest 
3. Provider Project Name and Folder 
4. Enter.

### Expected result

Project Structure should be created.

### Actual result

Error: Cannot find module 'yeoman-generator'
    at Function._load (C:/Users/gaditya2/AppData/Local/sfdx/client/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:102:42)
    at require (C:/Users/gaditya2/AppData/Local/sfdx/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:/Users/gaditya2/AppData/Local/sfdx/client/node_modules/salesforcedx-templates/lib/generators/projectGenerator.js:12:19)
    at Module._compile (C:/Users/gaditya2/AppData/Local/sfdx/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

### Additional information

_Feel free to attach a screenshot_.

![image](https://user-images.githubusercontent.com/59299135/72522625-bd59a100-3823-11ea-9785-0d8141a32d40.png)

**VS Code Version**:1.36.1

**SFDX CLI Version**: sfdx-cli 7.41.0 (core)

**OS and version**: Windows 10 Enterprise 1809

**Comment by brpowell** [comment]
Hi @gvadityagit, can you try running ‘sfdx update’? If you have already you may need to do it once more to fetch the correct build.

**Comment by gvadityagit** [comment]
@brpowell  👍 Thanks it worked

**Comment by gvadityagit** [comment]
I see nee issue after the update , now i am getting :  unable to authorize org , oauth generic token issue.

Its throwing kill process on port 1717 , 

even after ending through task manager and restarting system and vs code it still shows same
