### ISSUE TITLE
[WSL] Grep Is Not Working With log tail

### ISSUE THREAD

**Issue by nikhil-sfdev** [forcedotcom/salesforcedx-vscode#2147]
Piping grep with log tail in a wsl terminal but it is showing exceptions. Same command is working on command prompt with findstr.

### Steps To Reproduce:

1.  sfdx force:apex:log:tail -u username_production | grep USER_DEBUG

### Expected result

USER_DEBUG lines in log file

### Actual result

```
net.js:268
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:268:24)
    at createWritableStdioStream (internal/process/stdio.js:191:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:454:19
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at setupGlobalConsole (internal/bootstrap/node.js:407:41)
    at startup (internal/bootstrap/node.js:142:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### System Version Info
sfdx-cli/7.54.4-8ff9ba9cc5 win32-x64 node-v10.15.3

**Comment by lcampos** [comment]
Thanks for opening this issue @nikhil-sfdev . This is happening because the Salesforce CLI currently does not support WSL Terminal. Here are more details on what's supported (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm).

I'll close this for now but will consider this when the CLI looks at expanding supporting other command line clients.
cc @smaddox-sf @ntotten
