### ISSUE TITLE
Path doesnot exist error while creating project in vs code

### ISSUE THREAD

**Issue by AnupBandawar** [forcedotcom/salesforcedx-vscode#2360]
Starting SFDX: Create Project

11:58:51.468 sfdx force:project:create --projectname HelloWorld --outputdir f:\Salesforce Projects --template standard --manifest
(node:7988) [UnknownConfigKey Plugin: sfdx-cli] UnknownConfigKey Plugin: sfdx-cli: Unknown config key: disableTelemetry
module: @oclif/config@1.15.1
task: runHook prerun
plugin: sfdx-cli
root: C:\Program Files\Salesforce CLI\client
See more details with DEBUG=*
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\templates\project\standard\ScratchDef.json
    at EditionInterface.exports.copy (C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at ProjectGenerator.writing (C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\lib\generators\projectGenerator.js:57:17)
    at Object.<anonymous> (C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:395:23)
    at C:\Program Files\Salesforce CLI\client\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Program Files\Salesforce CLI\client\node_modules\run-async\index.js:26:19
    at C:\Program Files\Salesforce CLI\client\node_modules\salesforcedx-templates\node_modules\yeoman-generator\lib\index.js:396:9
    at processImmediate (internal/timers.js:439:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
11:58:54.915 sfdx force:project:create --projectname HelloWorld --outputdir f:\Salesforce Projects --template standard --manifest
 ended with exit code 0
![2020-07-18 (1)](https://user-images.githubusercontent.com/42398682/87846608-7a6ba980-c8ea-11ea-94c4-90f5a8e56a72.png)

**Comment by smaddox-sf** [comment]
Hi @AnupBandawar - Do you see this error if you create a project that doesn't have any spaces in the file path?

Can you also share the steps to reproduce this issue?

**Comment by AnupBandawar** [comment]
Hi @smaddox-sf I solved the issue by reinstalling the Salesforce CLI and also added path in both system as well as user variable.
