### ISSUE TITLE
Cannot find module 'shelljs' when running bootstrap script

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/salesforcedx-vscode#2771]
### Summary
I'm getting the following error when trying to build the extension locally (from _develop_ branch)
```
npm run-script bootstrap

> @ bootstrap /Users/mzeuli/VSCProjects/salesforcedx-vscode
> lerna bootstrap --no-ci -- --no-package-lock && node scripts/reformat-with-prettier

lerna notice cli v3.22.1
lerna info Bootstrapping 19 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 19 packages
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'shelljs'
Require stack:
- /Users/mzeuli/VSCProjects/salesforcedx-vscode/scripts/reformat-with-prettier.js
```

### Steps To Reproduce:

1.  Clone https://github.com/forcedotcom/salesforcedx-vscode
1.  Be sure you are checkout on the develop branch
1.  Run the bootstrap script (or `npm install`)

**VS Code Version**:
version 1.51

**SFDX CLI Version**:
sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**OS and version**:
MacOS Mojave 10.14.6

**Comment by lcampos** [comment]
hi @maaaaarco , are you running the bootstrap script before running `npm install` at the top level ? If that's the case then this is expected, the bootstrap script depends on certain dependencies (shelljs, lerna, etc) that get installed at the top level of the repo when running `npm install`.

If what you are experiencing is that this failure happens while running `npm install`(given bootstrap also runs as a postinstall step) then I might have to change my setup to try and repro this since I'm currently building the project using [volta](https://volta.sh/). Let me know and I'll take a second look.

**Comment by maaaaarco** [comment]
Hi @lcampos, just tried again, cloning the repo again and running `npm install`. Same issue.
```
$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> node@12.4.0 preinstall /Users/mzeuli/VSCProjects/salesforcedx-vscode/node_modules/node
> node installArchSpecificPackage

+ node-darwin-x64@12.4.0
added 1 package in 1.284s
found 0 vulnerabilities


> fsevents@1.2.13 install /Users/mzeuli/VSCProjects/salesforcedx-vscode/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> husky@1.3.1 install /Users/mzeuli/VSCProjects/salesforcedx-vscode/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> core-js@2.6.12 postinstall /Users/mzeuli/VSCProjects/salesforcedx-vscode/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> undefined postinstall /Users/mzeuli/VSCProjects/salesforcedx-vscode
> lerna bootstrap --no-ci -- --no-package-lock && node scripts/reformat-with-prettier

lerna notice cli v3.13.1
lerna info Bootstrapping 19 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 19 packages
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'shelljs'
Require stack:
- /Users/mzeuli/VSCProjects/salesforcedx-vscode/scripts/reformat-with-prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/mzeuli/VSCProjects/salesforcedx-vscode/scripts/reformat-with-prettier.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mzeuli/VSCProjects/salesforcedx-vscode/scripts/reformat-with-prettier.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined postinstall: `lerna bootstrap --no-ci -- --no-package-lock && node scripts/reformat-with-prettier`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the undefined postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mzeuli/.npm/_logs/2020-12-02T08_28_23_291Z-debug.log
```

**Comment by lcampos** [comment]
Ok, we haven't been able to replicate the issue on our side but we think it might be caused by `shelljs` not being an explicit dependency at the top level. It is a dependency on other modules we did define like `commitizen` and `shx`. Our theory is that we are using the `shelljs` installed by those dependencies but somehow you are not able to in your machine.

Could you confirm if the change in PR https://github.com/forcedotcom/salesforcedx-vscode/pull/2779 fixes the issue you are experiencing ?

**Comment by maaaaarco** [comment]
@lcampos yes it does! thanks ;)

**Comment by lcampos** [comment]
Glad that fixed the problem @maaaaarco , I've merged it to `develop` already. Thanks for reporting this and let us know if you need anything else.
