### ISSUE TITLE
[Found an unusual fix] --->  ISSUE LABEL:  Unsure if/how i broke "Report" Retrievals in all of my sfdx projects.  Reinstall didnt help. Happens on all projects (new and existing) when retrieving reports. :  SourceRetrieveCommand gives error "Expected metadata file at path" "Missing metadata file"  in \\AppData\\Local\\Temp\\sdx_sourceRetrieve_pkg_*\\unpackaged\\reports.

### ISSUE THREAD

**Issue by peternoges** [forcedotcom/salesforcedx-vscode#2841]
### Summary

**Summary:** 

- Video/mp4 added in "steps to reproduce" section

- The broken behavior is that "Report" retrievals fail.  They fail using sfdx retrieve commands, they fail using orgbrowser Report retrieval, and they fail using manifest/package.xml retrieval. 

- reinstalling has not helped (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm) despite similar reports saying it might (https://salesforce.stackexchange.com/a/328986) 

- Occurs on new sfdx projects too.  Just for the "report" metadata type.

**Did i cause the error locally on my machine? Or is it a bug? How can i fix it?**

- I still dont know what causes the error.  However one "common action i took on each machine just before seeing the errors" was that i did run several **thousand** sfdx force:source:retrieve commands in sequence  (in hindsight i can consolidate the calls, but regardless im well-under my 24hr api limit.) 

**Troubleshooting done so far:**

- Since seeing this error i cannot retrieve Reports via sfdx commands, nor can i retrieve Reports via orgbrowser right-click retrieve actions, neither work. Both give the same error message.  I've updated the cli, extensions, restarted vsc,  restarted my pc, deleted force-app/main/default/reports,   and deleted the sdx_sourceRetrieve_pkg folders in Local\\Temp in an effort to fix the issue but none of that worked.  I have toggled on/off the performance beta setting but that did not help either.   
- im well-under the 24hr api limit
- with "salesforcedx-vscode-core>Experimental: Deploy Retrieve" TURNED ON i tried a package.xml retrieval as seen below by right-clicking the manifest, and using "SFDX: Retrieve Source in Manifest from Org" but that gave me this other error: "Could not infer a metadata type"
![image](https://user-images.githubusercontent.com/7834562/103719216-63467400-4f7d-11eb-806d-164cc790f2a1.png)
- with "salesforcedx-vscode-core>Experimental: Deploy Retrieve" TURNED OFF the same package.xml retrieval gives me the error: "ERROR running force:source:retrieve:  Expected metadata file at path: C:\Users\peter\AppData\Local\Temp\sdx_sourceRetrieve_pkg_1609897675974\unpackaged\reports\ABM_Dashboard_Reports\Account_Maturity_Distribution.report-meta.xml"

 

**Questions:**

- how to fix the error message? 

- why is the error occurring? Can we prove or disprove its due to the aforementioned "common action i took on each machine just before seeing the errors" ?

### Steps To Reproduce: 
Here is a video repro .mp4: https://gust.box.com/s/7xz60xx364q5yyt85f9ea0jy4dcxzz2y

Retrieve any  existing Report from the OrgBrowser, or by package.xml retrieval,  or using the command below
sfdx force:source:retrieve --json --loglevel fatal -m Report:ABM_Dashboard_Reports/Account_Maturity_Distribution

### Expected result
Expect successful retrieve of Reports/ABM_Dashboard_Reports/Account_Maturity_Distribution

### Actual result

{
  "status": 1,
  "name": "Missing metadata file",
  "message": "Expected metadata file at path: C:\\Users\\peter\\AppData\\Local\\Temp\\sdx_sourceRetrieve_pkg_1609877053779\\unpackaged\\reports\\ABM_Dashboard_Reports\\Account_Maturity_Distribution.report-meta.xml",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "Missing metadata file: Expected metadata file at path: C:\\Users\\peter\\AppData\\Local\\Temp\\sdx_sourceRetrieve_pkg_1609877053779\\unpackaged\\reports\\ABM_Dashboard_Reports\\Account_Maturity_Distribution.report-meta.xml\n
  at FolderMetadataType.validateRetrievedMetadataPathExists (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\defaultMetadataType.js:112:25)\n    at FolderMetadataType.getRetrievedMetadataPath (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\folderMetadataType.js:52:21)\n    at SourceWorkspaceAdapter.processMdapiFileProperty (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:303:82)\n    at C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:166:22\n    at Array.forEach (<anonymous>)\n    at MdapiPullApi._syncDownSource (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:158:31)\n    at SourceRetrieve.retrieveFromManifest (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieve.js:177:64)\n    at async SourceRetrieve.retrieve (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieve.js:65:27)\n    at async SourceRetrieveCommand.execute (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieveCommand.js:32:16)\n    at async SourceRetrieveCommand.execLegacyCommand (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\n    at async SourceRetrieveCommand.run (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\commands\\force\\source\\retrieve.js:32:16)\n    at async SourceRetrieveCommand._run (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n    at async Config.runCommand (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js:32:20)\nOuter stack:\n    at Function.wrap (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at SourceRetrieveCommand.catch (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\n    at async SourceRetrieveCommand._run (C:\\Users\\peter\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runCommand (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js:32:20)",  "warnings": []
}

**VS Code Version**:
![image](https://user-images.githubusercontent.com/7834562/103693772-aa694080-4f4e-11eb-8df5-135a559cb200.png)

**SFDX CLI Version**:
sfdx-cli/7.83.0 win32-x64 node-v12.16.1
**OS and version**:
Microsoft Windows 10 Home (Version	10.0.18363 Build 18363)

**Comment by peternoges** [comment]
I stumbled into a workaround.   I had to do ALL of the following.  Its unusual and not-ideal;  is anyone else getting Report retrieval errors?  Here is how im currently working around it:
1. Locally Delete force-app/main/default/reports
2. Turn on Beta ( for some reason i cant retrieve reports without this on and first deleting my /reports locally) 
![image](https://user-images.githubusercontent.com/7834562/103697218-71cc6580-4f54-11eb-82bb-37e086dbd037.png)

**Comment by peternoges** [comment]
3rd update:  

This is broken in 1 of my projects,  but not the other projects.    (Same machine comparison)

At this point, I'm revising the Issue Title for accuracy.

**Comment by peternoges** [comment]
I have revised the issue description

**Comment by peternoges** [comment]
I just reformatted the post for clarity.  Thanks all!

**Comment by peternoges** [comment]
I just reformatted the post for clarity and added notes about Troubleshooting. Thanks all for helping!

**Comment by peternoges** [comment]
I've added more notes about Troubleshooting, but this is still an open/unsolved issue for me

**Comment by peternoges** [comment]
Another user had a similar issue (https://salesforce.stackexchange.com/a/328986).  They claimed reinstalling helped them,  but reinstalling has not solved the issue for me.

**Comment by peternoges** [comment]
Still an issue, I have added repro video: https://gust.box.com/s/7xz60xx364q5yyt85f9ea0jy4dcxzz2y

**Comment by peternoges** [comment]
hi @brpowell tldr is i cant retrieve any Reports in sfdx.  Error says its looking for a folder/file that doesnt exist. An uninstall/reinstall didnt help (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm).  Im pretty stumped.

Its reproducible on 3 of my windows machines and in all sfdx projects - all those scenarios show a similar style of error.  

Any tips?  i also raised sfdc support ticket, 40325102, and cited this issue #2841  in the same writeup. 

In a time-crunch, im looking for any alternative to downloading all report metadata.   Preferably not via sfdx commands because, as stated in this ticket, all sfdx commands that retrieve Report are broken for me.  I considered crafting a change set and using workbench to retrieve it but im trying to avoid chgsets retrieval because the 'add components to change set' frequently fails for me when adding several Reports to them via sfdc lex/classic ui )

Thanks everyone and anyone who can help.

**Comment by peternoges** [comment]
Update:  I think i fixed this,  but im testing and confirming that still.   The error message somehow changed and began to mention the survey path, so i added **surveySettings to forceignore and so far its allowing me to retrieve Reports again.  Very odd @brpowell.   I'll keep this open, how on earth could ignoring surveySettings be my answer for fixing Report retrievals?  Seems like a hack but it did fix my issue.  I saw the error, then seconds later added surveySettings to forceignore, then seconds later the error was gone.

**Comment by gillyspy** [comment]
for me it was `**/weblinks**` so weird.  Thanks for the tip! 🙏

**Comment by peternoges** [comment]
@gillyspy  super glad it helped - but who knows, maybe something else or this fixed it;  i cant say for sure, but i did write down what i thought i knew at the time.

**Comment by sivanandjothy** [comment]
Adding both surveySettings and weblinks to the .forceignore file did not help me. Can we have this issue re-opened until we have a definite solution identified, please?

**/surveySettings/**
**/weblinks/**

I am facing the same error while retrieving DashboardFolder, Dashboard, ReportFolder, Report using manifest\package.xml through VS Code 

unpackaged\reports\PROJECTNAMEReports\Orders-meta.xml: Could not infer a metadata type
