### ISSUE TITLE
Cannot update some extensions

### ISSUE THREAD

**Issue by dvon88** [forcedotcom/salesforcedx-vscode#2967]
### Summary
I cannot update the LWC, Apex, Apex Replay Debugger, or Salesforce CLI Integration extensions. VSCode extension panel says that all of these are able to be updated to 50.17.0, but clicking on the update button gives this error in the integrated output:

[2021-02-19 08:59:33.452] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at N.downloadInstallableExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:26659)
    at async N.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:23863)
[2021-02-19 09:01:46.226] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at N.downloadInstallableExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:26659)","    at async N.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:23863)"]
[2021-02-19 09:01:46.256] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at N.downloadInstallableExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:26659)
    at async N.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:49:23863)

I do not have any other SF extensions installed.

### Steps To Reproduce:

1. Go to extension panel
2. Find any of these extensions
3. Click the update button

### Expected result
Updated extensions.

### Actual result
Not updated extensions.

### Additional information
![image](https://user-images.githubusercontent.com/35981904/108470293-6cbc3f00-7292-11eb-9b45-6d01ffbe5a47.png)

**VS Code Version**:
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64

**SFDX CLI Version**:
sfdx-cli/7.85.1-2fb9e41053 linux-x64 node-v12.18.3

**OS and version**:
Ubuntu 20.04

**Comment by lcampos** [comment]
That stacktrace shows that the error is at VSCode level and not with the extensions. I've seen this sporadically happen in the past and I've solved it by deleting the extensions and triggering the download again. Let us know if this works for you.

**Comment by dvon88** [comment]
@lcampos that appears to have fixed it
