### ISSUE TITLE
Out of Memory error, sporadic errors

### ISSUE THREAD

**Issue by brianmfear** [forcedotcom/salesforcedx-vscode#3045]
### Summary

Apex Language Server runs out of memory, causes errors, performance issues.

### Steps To Reproduce:

1. Open a DX project.
1. Open an Apex class.
1. System stutters and freezes, 100% CPU, cannot move mouse, switch apps, etc for some time.
1. Hovering over functions shows an error in Output panel.

[Error - Time] Request textDocument/hover failed.
Message: Internal Error
Code: -32603
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class apex.jorje.lsp.impl.visitors.ReferenceSourceVisitor
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class apex.jorje.lsp.impl.visitors.ReferenceSourceVisitor
at apex.jorje.lsp.impl.hover.StandardHoverProvider.lambda$provideHover$0(StandardHoverProvider.java:77)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
...

Also getting:

 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 5883 ms.
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space

### Expected result

The server should not be crashing.

### Actual result

Frequent server crashes over the past few days.

### Additional information

**VS Code Version**: 

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**SFDX CLI Version**:

sfdx-cli/7.87.0 win32-x64 node-v14.6.0

**OS and version**:

Microsoft Windows [Version 10.0.19042.804]

Please feel free to contact me if you need more information.

**Comment by smaddox-sf** [comment]
Duplicate #2803
