### ISSUE TITLE
Salesforce ISV debugger is not launching  (VS Code Version 1.54.1)

### ISSUE THREAD

**Issue by maimoona-shahid** [forcedotcom/salesforcedx-vscode#3149]
When trying to launch the Apex Debugger from vscode, is does not launch and ends up with Internal error and below message in output console.

[Error - 12:15:28 PM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

Apr 14, 2021 12:17:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space

**Here is the Launch.json file**

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Apex Debugger",
      "type": "apex",
      "request": "launch",
      "userIdFilter": [],
      "requestTypeFilter": [],
      "entryPointFilter": "",
      "sfdxProject": "${workspaceRoot}",
      "connectType": "ISV_DEBUGGER"
    }
  ]
}

**Steps To Reproduce:**
Push the ' Start debugging' button in VSCode

**Expected result**
Apex debugger should have been started.

**Actual result**
Keeps Loading for a while and then ends up with internal error

**Comment by sfsholden** [comment]
Hi @maimoona-shahid, thank you for reaching out to us about this issue.

If you try adding more memory following [this](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup) resource, does this unblock you? 

Please also confirm - is this new behavior or is this your first time using the ISV Debugger?


Thank you in advance.
