### ISSUE TITLE
"sfdx force:apex:test:run" and "sfdx force:apex:test:report" --wait and --codecoverage options not functioning as expected. 

### ISSUE THREAD

**Issue by conundrum1** [forcedotcom/salesforcedx-vscode#3172]
### Summary

Summary:

When running, "sfdx force:apex:test:run", it ends after 180 minutes, even though -w option is set to longer wait time (i.e. 1440 minutes).  Also, test results and coverage report are not returned, even when running the "sfdx force:apex:test:report" command, afterward.  

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

In the previous version of the sfdx cli (7.94.3),  we received the following expected results:

For the "sfdx force:apex:test:run -r human -c -l RunLocalTests -w 1440 --verbose" command, we expect to see the following messages while tests are running:

Listning for results
Invoking Apex tests using UID...
Started async test run job: 7072C00001gPNb1QAG
Processing event for job 7072C00001gPNb1QAG
Processing event for job 7072C00001gPNb1QAG
Processing event for job 7072C00001gPNb1QAG
...

Once test run completes, expect to see the test results and the code coverage report in human readable format.

Retrieving test results for job 7072C00001gPNb1QAG...
=== Apex Code Coverage
...

### Actual result

sfdx force:apex:test:run -r human -c -l RunLocalTests -w 1440 --verbose 

Even though we have wait time set to 1440 minutes, the test run times out and the job ends after 180 minutes.  

When it ends after 180 minute, it gives following error:

Error: 403::Unknown client
    at Object.incoming (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/lib/src/streaming/streamingClient.js:62:27)
    at pipe (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:932:43)
    at klass.pipeThroughExtensions (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:934:5)
    at klass._receiveMessage (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1413:10)
    at klass.handler (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:795:41)
    at klass.EventEmitter.emit (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:236:17)
    at klass.handleResponse (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1580:10)
    at klass._receive (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1740:24)
    at IncomingMessage.<anonymous> (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:2724:14)
    at IncomingMessage.emit (node:events:381:22)
Error: 403::Unknown client
    at Object.incoming (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/lib/src/streaming/streamingClient.js:62:27)
    at pipe (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:932:43)
    at klass.pipeThroughExtensions (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:934:5)
    at klass._receiveMessage (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1413:10)
    at klass.handler (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:795:41)
    at klass.EventEmitter.emit (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:236:17)
    at klass.handleResponse (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1580:10)
    at klass._receive (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1740:24)
    at IncomingMessage.<anonymous> (/home/svc_devopsci/.local/share/sfdx/client/7.97.0-c130e7a/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:2724:14)
    at IncomingMessage.emit (node:events:381:22)
ERROR running force:apex:test:run:  Unknown error in Apex Library: 403::Unknown client

However, the test run continues running in the Salesforce org.  While it is running, if we attempt the following command to retrieve a report with the test run job id:

sfdx force:apex:test:report -i 7072C00001gPNb1QAG -c -r human 

We received the following error:
ERROR running force:apex:test:report:  Cannot read property 'records' of null

Once the test run completes in the org,  when we attempt the same command again:
sfdx force:apex:test:report -i 7072C00001gPNb1QAG -c -r human 

It returns the following error:
ERROR running force:apex:test:report:  <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.97.0 linux-x64 node-v15.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.1 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ apex 0.1.21 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.0.5 (core)
├─ org 1.6.2 (core)
├─ schema 1.0.5 (core)
├─ templates 51.3.0 (core)
├─ user 1.2.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.11 (core)
sfdx-cli 7.97.0 (core)
telemetry 1.1.2 (core)

**OS and version**:
linux-x64

**Comment by AnanyaJha** [comment]
Hi @conundrum1 thanks for reporting this! We'll work on reproducing this behavior so we can see what might be going on. In previous versions of the cli, how long did the test typically run for?

**Comment by conundrum1** [comment]
Hi @AnanyaJha , thanks for checking into what might be going on with this issue. In previous versions of the cli, typically our tests would run for about 4 - 5 hours.

**Comment by AnanyaJha** [comment]
Hi @conundrum1 it looks like there's a few different things that could be happening here, it's possible the Streaming API is losing connection which is why the tests are timing out early. We'll work on debugging what might be happening in this scenario and will update this thread with a fix once we have it, thanks!

**Comment by dragomir-enachi-ibm** [comment]
also happens to us. when is it going to be resolved?

**Comment by SimonShepherd** [comment]
We got the same 403 errors today in our Ci flow

**Comment by lionelbethoux** [comment]
We are facing the same 403 errors

**Comment by mrichmon12** [comment]
Also getting this consistently now. It was more sporadic before, but it happens every day on multiple CI build nodes now.

**Comment by AnanyaJha** [comment]
Hi all, thanks for reaching out. Can you please post what versions of the Apex plugin your CLI is currently using? This can be found by running `sfdx plugins --core`. We recently submitted a fix that should address part of this issue with release `0.2.3 `of the Apex plugin, so if you find you are behind on the version then please try running `sfdx plugins:install apex`.

**Comment by mrichmon12** [comment]
Our nodes were using `apex 0.2.2 (core)`, so I'll update them and report back.

**Comment by mrichmon12** [comment]
@AnanyaJha I'm seeing a different error now.

```
+ sfdx force:apex:test:run --targetusername **** --testlevel RunLocalTests --resultformat junit --codecoverage --wait 480 --verbose
ERROR running force:apex:test:run:  <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
```

This error is received after about 2 hours into the job running.

**Comment by AnanyaJha** [comment]
Thanks @mrichmon12 ! This matches what we see locally as well - is it possible for you to access the test run in Developer Console? And see if the tests are still running in the org?

**Comment by alan-morey** [comment]
@AnanyaJha  For what it's worth, updating the apex plugin from 0.2.2 to 0.2.3 worked for me.

```
+ sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.110.0",
	"architecture": "linux-x64",
	"nodeVersion": "node-v12.22.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.2 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.4.0-3 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-trust 3.6.0 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.3",
		"auth 1.7.1 (core)",
		"config 1.2.13 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.5.2 (core)",
		"generator 1.1.8 (core)",
		"limits 1.2.1 (core)",
		"org 1.6.7 (core)",
		"salesforce-alm 52.1.0 (core)",
		"schema 1.0.8 (core)",
		"sfdx-cli 7.110.0 (core)",
		"telemetry 1.2.2 (core)",
		"templates 52.1.0 (core)",
		"user 1.3.1 (core)"
	],
	"osVersion": "Linux 3.10.0-1160.24.1.el7.x86_64"
}
```

I've had 2 successful runs of a nightly scheduled job on my Jenkins server that runs all tests on a sandbox. It takes just under 6 hours to run all tests using following command:

`sfdx force:apex:test:run -w -1 -l RunLocalTests --outputdir=build/tests --resultformat=junit --codecoverage`

Prior to updating the apex plugin the job had been failing every night for well over a month with the the following error: 

```
Error: 403::Unknown client
    at Object.incoming (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/lib/src/streaming/streamingClient.js:62:27)
    at pipe (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:932:43)
    at klass.pipeThroughExtensions (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:934:5)
    at klass._receiveMessage (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1413:10)
    at klass.handler (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:795:41)
    at klass.EventEmitter.emit (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:236:17)
    at klass.handleResponse (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1580:10)
    at klass._receive (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1740:24)
    at IncomingMessage.<anonymous> (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:2724:14)
    at IncomingMessage.emit (events.js:326:22)
Error: 403::Unknown client
    at Object.incoming (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/lib/src/streaming/streamingClient.js:62:27)
    at pipe (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:932:43)
    at klass.pipeThroughExtensions (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:934:5)
    at klass._receiveMessage (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1413:10)
    at klass.handler (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:795:41)
    at klass.EventEmitter.emit (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:236:17)
    at klass.handleResponse (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1580:10)
    at klass._receive (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:1740:24)
    at IncomingMessage.<anonymous> (/data1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_12/lib/node_modules/sfdx-cli/node_modules/@salesforce/apex-node/node_modules/faye/node/faye-node.js:2724:14)
    at IncomingMessage.emit (events.js:326:22)
ERROR running force:apex:test:run:  Unknown error in Apex Library: 403::Unknown client
```

**Comment by mrichmon12** [comment]
@AnanyaJha it's not running now, but I'm not certain that the run wasn't still executing when we received the error.

**Comment by mrichmon12** [comment]
@AnanyaJha I ran another one to observe this more closely. The 414 error is returned when the test run completes.

**Comment by AnanyaJha** [comment]
@mrichmon12 To confirm, with the new version `0.2.3`, you are no longer seeing the `Unknown error in Apex Library: 403::Unknown client` but instead `<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>`. Or were you receiving the _latter_ error with all versions?

**Comment by mrichmon12** [comment]
@AnanyaJha I looked back through the build history for the last month that was on `apex 0.2.2`. We were mostly receiving `403::Unknown client`, but were also seeing a number of  `414: URI Too Long` errors. There were two occurrences of `431: Request Header Fields Too Large`.

We haven't seen the 403 error since upgrading to `apex 0.2.3`, it has been all the 414 error.

**Comment by dieffrei** [comment]
@AnanyaJha we started to have the same issue as described

**Comment by mrichmon12** [comment]
@AnanyaJha a couple of other failure variations to report. Not sure if they are related or not, but the end result is the same, no unit test results or code coverage results. 

````
02:37:21 + sfdx force:apex:test:run --targetusername **** --testlevel RunLocalTests --resultformat junit --codecoverage --wait 480 --verbose
06:56:17 (node:2628) Warning: The query result is missing 38203 records due to a 40000 record limit. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 78203 or greater than 40000.
06:56:17 (Use `node --trace-warnings ...` to show where the warning was created)
06:56:19 <?xml version="1.0" encoding="UTF-8"?>
06:56:19 <testsuites>
.... (junit test results) ....
06:56:19 + sfdx force:apex:test:report --targetusername **** -i --resultformat tap --codecoverage
06:56:20 ERROR running force:apex:test:report:  Unexpected argument: tap
````
We have seen this error before and have set the SFDX_MAX_QUERY_LIMIT variable in increasing increments (25k, 28k, 35k, 40k) over the past month. I'm not sure what is being queried here that is returning so many results and why it keeps increasing.

```
02:37:29 + sfdx force:apex:test:run --targetusername **** --testlevel RunLocalTests --resultformat junit --codecoverage --wait 480 --verbose
03:04:37 (node:17431) UnhandledPromiseRejectionWarning: ERROR_HTTP_502: <!DOCTYPE html> 
.... (a bunch of CSS) ....
03:07:40     <div class="slds-text-longform">
03:07:40       <h3>An unexpected connection error occurred.</h3>
03:07:40       <p class="slds-text-body"> Try refreshing the page or visit our <a href="https://status.salesforce.com/"
03:07:40           target="_blank">status page</a> for more information.
03:07:40         <br><b>Ref1: c9c8e8b7dd5b309e28c0a6271647e99a
03:07:40         Ref2: 2021-08-12T07:05:46+00:00
03:07:40         Ref3: <span style="text-transform:uppercase">iad</span></b></p>
03:07:40       <span class="site-logo">
03:07:40         <img src="https://www.lightningdesignsystem.com/assets/images/logo.svg" alt"logo" class="logo">
03:07:40       </span>
03:07:40     </div>
03:07:40   </div>
03:07:40   <footer class="slds-align_absolute-center">
03:07:40     <p class="origin-p">This error originated from Salesforce Edge.</p>
03:07:40   </footer>
03:07:40 </body>
03:07:40 
03:07:40     at HttpApi.getError (/home/ci_dev_builds/.local/share/sfdx/node_modules/@salesforce/plugin-apex/node_modules/jsforce/lib/http-api.js:250:13)
03:07:40     at /home/ci_dev_builds/.local/share/sfdx/node_modules/@salesforce/plugin-apex/node_modules/jsforce/lib/http-api.js:95:22
03:07:40     at tryCallOne (/home/ci_dev_builds/.local/share/sfdx/node_modules/@salesforce/plugin-apex/node_modules/promise/lib/core.js:37:12)
03:07:40     at /home/ci_dev_builds/.local/share/sfdx/node_modules/@salesforce/plugin-apex/node_modules/promise/lib/core.js:123:15
03:07:40     at flush (/home/ci_dev_builds/.local/share/sfdx/node_modules/@salesforce/plugin-apex/node_modules/asap/raw.js:50:29)
03:07:40     at processTicksAndRejections (internal/process/task_queues.js:77:11)
03:07:40 (node:17431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
07:11:00 ERROR running force:apex:test:run:  <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
```
Seems like there was an unhandled network exception, but the command kept running and eventually returned the `URI Too Long` error we have been seeing since May/June.

**Comment by AnanyaJha** [comment]
Hi @mrichmon12 thanks for sharing the data. We've been able to reproduce the issue locally as well and have logged a bug to address it. We'll be sure to update the thread with more info once we have it!

**Comment by bdovh** [comment]
I have the following error. Is this the same error or a new one?

echo $(sfdx force:apex:test:run -l RunLocalTests --loglevel=trace -y -c -r json -d ./tests/apex -w 999999) > tests.json
WARNING: WARNING: In the Summer ’21 release, we'll rename or remove some of the output files that are created when you run force:apex:test:run or force:apex:test:report with the --outputdir (-d) parameter.  This breaking change could impact your CI/CD scripts if they reference specific filenames. See https://sfdc.co/apex-test-updates for details

CLIError: timed out
    at Object.error (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:12[4](https://github.com/LinkSquares/salesforce-finalize/actions/runs/4023470169/jobs/6914377625#step:24:5):[9](https://github.com/LinkSquares/salesforce-finalize/actions/runs/4023470169/jobs/6914377625#step:24:10)) {
  oclif: { exit: 2 },
  code: undefined
}
ERROR running force:apex:test:run:  Unknown error in Apex Library: timed out

**Comment by adrianioana** [comment]
> I have the following error. Is this the same error or a new one?
> 
> echo $(sfdx force:apex:test:run -l RunLocalTests --loglevel=trace -y -c -r json -d ./tests/apex -w 999999) > tests.json WARNING: WARNING: In the Summer ’21 release, we'll rename or remove some of the output files that are created when you run force:apex:test:run or force:apex:test:report with the --outputdir (-d) parameter. This breaking change could impact your CI/CD scripts if they reference specific filenames. See https://sfdc.co/apex-test-updates for details
> 
> CLIError: timed out at Object.error (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15) at /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66 at async flush (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:12[4](https://github.com/LinkSquares/salesforce-finalize/actions/runs/4023470169/jobs/6914377625#step:24:5):[9](https://github.com/LinkSquares/salesforce-finalize/actions/runs/4023470169/jobs/6914377625#step:24:10)) { oclif: { exit: 2 }, code: undefined } ERROR running force:apex:test:run: Unknown error in Apex Library: timed out

Hi team,

I am also getting the following errors:

CLIError: timed out
    at Object.error (/opt/hostedtoolcache/node/18.12.1/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /opt/hostedtoolcache/node/18.12.1/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/opt/hostedtoolcache/node/18.12.1/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:124:9) {
  oclif: { exit: 2 },
  code: undefined
}
ERROR running force:apex:test:report:  Unknown error in Apex Library: timed out

**Comment by gourdeepti** [comment]
Hi Team,
I am facing the same issue 
Error: 403::Unknown client
    at Object.incoming (/usr/local/lib/sfdx/node_modules/@salesforce/apex-node/lib/src/streaming/streamingClient.js:62:27)

Is there any fix for this issue.

**Comment by AnanyaJha** [comment]
Hi @gourdeepti - can you please open a new issue with the details of what you're facing? Thanks!
