### ISSUE TITLE
Unable to get Junit test result format when running Apex tests

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/salesforcedx-vscode#3359]
### Summary

Error "_Invalid time value_" occurs when executing `force:apex:test:run` or `force:apex:test:report` with the result format specified as `-r junit`

### Steps To Reproduce:

MyTest.cls
```
@IsTest(isParallel = true)
class MyTest {
    @IsTest
    static void shouldFail() {
        System.assertEquals(1, 1 + 1);
    }

    @IsTest
    static void shouldPass() {
        System.assertEquals(2, 1 + 1);
    }
}
```

Run apex test and specify result format as junit:
```
sfdx force:apex:test:run --wait -1 -r junit -t MyTest
```

### Expected result

Expected test results written to standard output in Junit format

### Actual result
Results are output as JSON and error occurs

```
$ sfdx force:apex:test:run --wait -1 -r junit -t MyTest
{
  "summary": {
    "outcome": "Failed",
    "testsRan": 2,
    "passing": 1,
    "failing": 1,
    "skipped": 0,
    "passRate": "50%",
    "failRate": "50%",
    "skipRate": "0%",
    "testStartTime": "Thu Jun 24 2021 12:30:14 p.m.",
    "testExecutionTimeInMs": 34,
    "testTotalTimeInMs": 34,
    "commandTimeInMs": 287,
    "hostname": "https://example--alandev01.my.salesforce.com",
    "orgId": "00D1F000000YO2SUAW",
    "username": "alan.morey@example.net.alandev01",
    "testRunId": "7071F0000208syH",
    "userId": "00530000003ZbzsAAC"
  },
  "tests": [
    {
      "id": "07M1F00000Mb95RUAR",
      "queueItemId": "7091F000002PGCzQAO",
      "stackTrace": "Class.Assert.fail: line 95, column 1\nClass.Assert.failNotEquals: line 145, column 1\nClass.Assert.equals: line 127, column 1\nClass.Assert.equals: line 108, column 1\nClass.MyTest.shouldFail: line 5, column 1",
      "message": "System.AssertException: Assertion Failed: Expected: <1>, Actual: <2>",
      "asyncApexJobId": "7071F0000208syHQAQ",
      "methodName": "shouldFail",
      "outcome": "Fail",
      "apexLogId": null,
      "apexClass": {
        "id": "01p1F00000JCxPPQA1",
        "name": "MyTest",
        "namespacePrefix": null,
        "fullName": "MyTest"
      },
      "runTime": 14,
      "testTimestamp": "2021-06-24T19:30:15.000+0000",
      "fullName": "MyTest.shouldFail",
      "diagnostic": {
        "exceptionMessage": "System.AssertException: Assertion Failed: Expected: <1>, Actual: <2>",
        "exceptionStackTrace": "Class.Assert.fail: line 95, column 1\nClass.Assert.failNotEquals: line 145, column 1\nClass.Assert.equals: line 127, column 1\nClass.Assert.equals: line 108, column 1\nClass.MyTest.shouldFail: line 5, column 1",
        "className": "Assert",
        "compileProblem": "",
        "lineNumber": 95,
        "columnNumber": 1
      }
    },
    {
      "id": "07M1F00000Mb95SUAR",
      "queueItemId": "7091F000002PGCzQAO",
      "stackTrace": null,
      "message": null,
      "asyncApexJobId": "7071F0000208syHQAQ",
      "methodName": "shouldPass",
      "outcome": "Pass",
      "apexLogId": null,
      "apexClass": {
        "id": "01p1F00000JCxPPQA1",
        "name": "MyTest",
        "namespacePrefix": null,
        "fullName": "MyTest"
      },
      "runTime": 20,
      "testTimestamp": "2021-06-24T19:30:38.000+0000",
      "fullName": "MyTest.shouldPass"
    }
  ]
}
Encountered an error when processing test results
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at JUnitReporter.format (/home/alan/.local/share/sfdx/client/7.107.0-621a7d2/node_modules/@salesforce/apex-node/lib/src/reporters/junitReporter.js:19:65)
    at Run.logJUnit (/home/alan/.local/share/sfdx/client/7.107.0-621a7d2/node_modules/@salesforce/plugin-apex/lib/commands/force/apex/test/run.js:164:30)
    at Run.<anonymous> (/home/alan/.local/share/sfdx/client/7.107.0-621a7d2/node_modules/@salesforce/plugin-apex/lib/commands/force/apex/test/run.js:83:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/alan/.local/share/sfdx/client/7.107.0-621a7d2/node_modules/@salesforce/plugin-apex/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Additional information

Same result occurs when using `force:apex:test:report`

```
sfdx force:apex:test:run --wait -1 -r junit -i 7071F0000208syH
```

If the output directory flag is also specified, the output is slightly different but the result is still an error.

```
$ sfdx force:apex:test:run -r junit -w -1 -t MyTest -d test-results
WARNING: WARNING: In the Summer ’21 release, we'll rename or remove some of the output files that are created when you run force:apex:test:run or force:apex:test:report with the --outputdir (-d) parameter.  This breaking change could impact your CI/CD scripts if they reference specific filenames. See https://sfdc.co/apex-test-updates for details

ERROR running force:apex:test:run:  Invalid time value
```

No output files are written and the output directory `test-results` does not gets created.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `sfdx-cli/7.107.0 linux-x64 node-v14.17.1`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
 sfdx plugins --core
@alan-morey/sfdx-plugin 0.0.0 (link) /home/alan/repos/alan-morey-sfdx-plugin                                                                                                   
@oclif/plugin-autocomplete 0.3.0                                                                                                                                               
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-scanner 2.9.2
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
apexlink 1.3.2
auth 1.6.1 (core)
config 1.2.8 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.1.7 (core)
gr-sfdx-plugin 0.0.0 (link) /home/alan/repos/salesforce/gr-sfdx-plugin
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.107.0 (core)
telemetry 1.2.2 (core)
templates 52.0.0 (core)                                                                                                                                                        
user 1.3.0 (core)   
```

**OS and version**: Ubuntu 18.04.5 LTS

**Comment by AnanyaJha** [comment]
Hi @alan-morey thanks for reporting this! Unfortunately, we weren't able to repro this locally. Can you provide us with a sample repository to test out this scenario?

**Comment by alan-morey** [comment]
@AnanyaJha Did you try to reproduce on Linux?

FYI, it does not seem to be a bug on Windows, my team are on Windows machines and `-r junit` works as expected for them.
