### ISSUE TITLE
Unable to deploy CustomField CustomObject metadata

### ISSUE THREAD

**Issue by JSaterdalen** [forcedotcom/salesforcedx-vscode#3634]
### Summary

When editing custom fields in VS Code, I am unable to deploy back to my sandbox due to the following error:

`An error was encountered during conflict detection. MetadataTransferError: Metadata API request failed: Component conversion failed: Method not implemented`

Deploying with the terminal using the CLI works as intended. E.g. `sfdx force:source:deploy -m "CustomObject:Account" `

### Steps To Reproduce:

1.  Add a CustomObject or CustomField to package.xml
    ```
    <types>
      <members>Account.Test_Field__c</members>
      <name>CustomField</name>
    </types>
    ```
1.  Edit the related `Test_Field__c.field-meta.xml` file
1. Right click on the file, parent folder, or "force-app/main/default" folder and select "SFDX: Deploy source to org"

### Expected result

The field metadata should be deployed to my org without error. 

### Actual result

VS Code output:

```
14:26:41.973 Starting Conflict Detection

An error was encountered during conflict detection. MetadataTransferError: Metadata API request failed: Component conversion failed: Method not implemented
```

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v53.2

**SFDX CLI Version**: 7.125.0

**OS and version**: macOS Monterey, but occurred in Big Sur previously.

**Comment by jeffb-sfdc** [comment]
I've been able to reproduce this.  There's an error taking place in metadataConverter.js `convert()`.  The stack is:
```
Method not implemented
	at ZipTreeContainer.readFileSync (salesforcedx-vscode-core/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/treeContainers.js:121:15)
	at SourceComponent.parseXmlSync (salesforcedx-vscode-core/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/sourceComponent.js:95:40)
	at SourceComponent.getNonDecomposedChildren (salesforcedx-vscode-core/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/sourceComponent.js:175:29)
```

**Comment by mani2246** [comment]
A temporary fix for this is to Disable conflict detection during deploy in vscode.

1. Select File > Preferences > Settings (Windows or Linux) or Code > Preferences > Settings (macOS).
2. Deselect (uncheck) Detect Conflicts At Sync.
![image](https://user-images.githubusercontent.com/13785524/144708282-34c86691-6d3e-4a63-927b-41c704881e30.png)

**Comment by floralan** [comment]
@JSaterdalen We're still working on fixing this issue, please stay tuned.

**Comment by CristiCanizales** [comment]
Hi, I'll be closing this as we've done testing to confirm it's not an issue anymore. Feel free to open a new one if it is still an issue.
