### ISSUE TITLE
Apex Language Server Crashing during intellisense suggestion generation

### ISSUE THREAD

**Issue by cnaccio** [forcedotcom/salesforcedx-vscode#3739]
I'm running into a similar/related issue which appears to occur randomly while writing Apex code. The error below occurred when starting to type System.today(), basically as soon as intellisense tried to generate suggestions after typing the letter S, the language server crashed with the error below, and stopped offering suggestions. 

**System Configuration**

VS CODE
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z (3 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

SALESFORCE CLI INTEGRATION
v53.8.1

**Error dump from output panel**

```
Jan 01, 2022 1:46:15 AM apex.jorje.semantic.compiler.CodeUnit additionalValidate
INFO: unexpected error during apex additional validate:

public with sharing class edge_FulfillmentService {
    
    
    public class FulfillmentServiceException extends Exception {}

    
    public static AcctSeedERP__Sales_Order_Inventory_Movement__c allocateSalesOrderLine(
        Id soLineId,
        Id inventoryBalanceId,
        Double quantity
    ) {

        // Allocate sales order line by creating required sales order inventory movements
        AcctSeedERP__Sales_Order_Inventory_Movement__c soInventoryMovement;
        soInventoryMovement = new AcctSeedERP__Sales_Order_Inventory_Movement__c(
            AcctSeedERP__Sales_Order_Line__c = soLineId,
            AcctSeedERP__Inventory_Balance__c = inventoryBalanceId,
            AcctSeedERP__Movement_Date__c = System.today(),
            AcctSeedERP__Quantity__c = invAllocation.QuantityAllocated,
            AcctSeedERP__Unit_Cost__c = soLine.ProductUnitCost == null ? 0 : soLine.ProductUnitCost,

            AcctSeedERP__Movement_Date__c = S
        );

        // Save changes
        insert soInventoryMovement;

        // Return results
        return soInventoryMovement;
    }
}
java.lang.NullPointerException
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression$NameValueParameter.getSObjectField(NewKeyValueObjectExpression.java:223)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.lambda$visitEnd$0(SObjectCompletionActivationStrategy.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:133)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:78)
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression.traverse(NewKeyValueObjectExpression.java:95)
	at apex.jorje.semantic.ast.expression.AssignmentExpression.traverse(AssignmentExpression.java:111)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.traverse(ExpressionStatement.java:53)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.compiler.CodeUnit.additionalValidate(CodeUnit.java:270)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:178)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:97)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy.analyze(SObjectCompletionActivationStrategy.java:66)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.constructorContext(ConstructorContextUtil.java:64)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.isConstructorContext(ConstructorContextUtil.java:51)
	at apex.jorje.lsp.impl.completions.TypesCompletionStrategy.lambda$provideCompletions$1(TypesCompletionStrategy.java:84)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.completions.TypesCompletionStrategy.provideCompletions(TypesCompletionStrategy.java:82)
	at apex.jorje.lsp.impl.completions.ApexCompletionStrategyAggregator.provideCompletions(ApexCompletionStrategyAggregator.java:101)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$completion$0(StandardTextDocumentService.java:126)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Jan 01, 2022 1:46:15 AM apex.jorje.semantic.compiler.CodeUnit additionalValidate
INFO: unexpected error during apex additional validate:

public with sharing class edge_FulfillmentService {
    
    
    public class FulfillmentServiceException extends Exception {}

    
    public static AcctSeedERP__Sales_Order_Inventory_Movement__c allocateSalesOrderLine(
        Id soLineId,
        Id inventoryBalanceId,
        Double quantity
    ) {

        // Allocate sales order line by creating required sales order inventory movements
        AcctSeedERP__Sales_Order_Inventory_Movement__c soInventoryMovement;
        soInventoryMovement = new AcctSeedERP__Sales_Order_Inventory_Movement__c(
            AcctSeedERP__Sales_Order_Line__c = soLineId,
            AcctSeedERP__Inventory_Balance__c = inventoryBalanceId,
            AcctSeedERP__Movement_Date__c = System.today(),
            AcctSeedERP__Quantity__c = invAllocation.QuantityAllocated,
            AcctSeedERP__Unit_Cost__c = soLine.ProductUnitCost == null ? 0 : soLine.ProductUnitCost,

            AcctSeedERP__Movement_Date__c = S
        );

        // Save changes
        insert soInventoryMovement;

        // Return results
        return soInventoryMovement;
    }
}
java.lang.NullPointerException
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression$NameValueParameter.getSObjectField(NewKeyValueObjectExpression.java:223)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.lambda$visitEnd$0(SObjectCompletionActivationStrategy.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:133)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:78)
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression.traverse(NewKeyValueObjectExpression.java:95)
	at apex.jorje.semantic.ast.expression.AssignmentExpression.traverse(AssignmentExpression.java:111)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.traverse(ExpressionStatement.java:53)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.compiler.CodeUnit.additionalValidate(CodeUnit.java:270)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:178)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:97)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy.analyze(SObjectCompletionActivationStrategy.java:66)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.constructorContext(ConstructorContextUtil.java:64)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.isConstructorContext(ConstructorContextUtil.java:51)
	at apex.jorje.lsp.impl.completions.SystemNamespaceCompletionStrategy.lambda$provideCompletions$1(SystemNamespaceCompletionStrategy.java:79)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.completions.SystemNamespaceCompletionStrategy.provideCompletions(SystemNamespaceCompletionStrategy.java:76)
	at apex.jorje.lsp.impl.completions.ApexCompletionStrategyAggregator.provideCompletions(ApexCompletionStrategyAggregator.java:101)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$completion$0(StandardTextDocumentService.java:126)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Jan 01, 2022 1:46:15 AM apex.jorje.semantic.compiler.CodeUnit additionalValidate
INFO: unexpected error during apex additional validate:

public with sharing class edge_FulfillmentService {
    
    
    public class FulfillmentServiceException extends Exception {}

    
    public static AcctSeedERP__Sales_Order_Inventory_Movement__c allocateSalesOrderLine(
        Id soLineId,
        Id inventoryBalanceId,
        Double quantity
    ) {

        // Allocate sales order line by creating required sales order inventory movements
        AcctSeedERP__Sales_Order_Inventory_Movement__c soInventoryMovement;
        soInventoryMovement = new AcctSeedERP__Sales_Order_Inventory_Movement__c(
            AcctSeedERP__Sales_Order_Line__c = soLineId,
            AcctSeedERP__Inventory_Balance__c = inventoryBalanceId,
            AcctSeedERP__Movement_Date__c = System.today(),
            AcctSeedERP__Quantity__c = invAllocation.QuantityAllocated,
            AcctSeedERP__Unit_Cost__c = soLine.ProductUnitCost == null ? 0 : soLine.ProductUnitCost,

            AcctSeedERP__Movement_Date__c = S
        );

        // Save changes
        insert soInventoryMovement;

        // Return results
        return soInventoryMovement;
    }
}
java.lang.NullPointerException
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression$NameValueParameter.getSObjectField(NewKeyValueObjectExpression.java:223)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.lambda$visitEnd$0(SObjectCompletionActivationStrategy.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:133)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:78)
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression.traverse(NewKeyValueObjectExpression.java:95)
	at apex.jorje.semantic.ast.expression.AssignmentExpression.traverse(AssignmentExpression.java:111)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.traverse(ExpressionStatement.java:53)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.compiler.CodeUnit.additionalValidate(CodeUnit.java:270)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:178)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:97)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy.analyze(SObjectCompletionActivationStrategy.java:66)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.constructorContext(ConstructorContextUtil.java:64)
	at apex.jorje.lsp.impl.completions.SObjectFieldNamesCompletionStrategy.lambda$provideCompletions$1(SObjectFieldNamesCompletionStrategy.java:76)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.completions.SObjectFieldNamesCompletionStrategy.provideCompletions(SObjectFieldNamesCompletionStrategy.java:74)
	at apex.jorje.lsp.impl.completions.ApexCompletionStrategyAggregator.provideCompletions(ApexCompletionStrategyAggregator.java:101)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$completion$0(StandardTextDocumentService.java:126)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```

_Originally posted by @cnaccio in https://github.com/forcedotcom/salesforcedx-vscode/issues/2268#issuecomment-1003521021_

**Comment by randi274** [comment]
@cnaccio have you tried reinstalling the extensions, as mentioned over in 2268?
