### ISSUE TITLE
Bug while install LWC extension

### ISSUE THREAD

**Issue by saurabhsoodsfdc** [forcedotcom/salesforcedx-vscode#3862]
### Summary
[2022-02-25 21:02:30.801] [renderer1] [error] [Extension Host] Cannot find en-gb, defaulting to en
[2022-02-25 21:02:30.802] [renderer1] [error] [Extension Host] Cannot find en-gb, defaulting to en
[2022-02-25 21:03:33.467] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at D.downloadInstallableExtension (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)","    at async D.doRun (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)"]
[2022-02-25 21:03:33.492] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at D.downloadInstallableExtension (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)
    at async D.doRun (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by jag-sfdc** [comment]
@saurabhsoodsfdc - We are not able to repro this locally. This might be a one-off issue because a corrupt vsix file was downloaded from the marketplace. Can you please give it another try?

**Comment by saurabhsoodsfdc** [comment]
@jag-sfdc I have been doing uninstalling and re-installing VS code and Salesforce Extension Pack since last Thursday but no luck!!
I have cross-checked with my co-workers. No one facing this issue. 

Using Macbook: Version 12.2.1 
- [VS Code Download link](https://code.visualstudio.com/download)
- [Salesforce Extension Pack Download link](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) 

Error Message while installing Salesforce Extension Pack Extension.
`[2022-02-28 14:30:00.923] [renderer3] [error] ["Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found","    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17874","    at Array.reduce (<anonymous>)","    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17860)","    at O.joinAllSettled (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9049)","    at async O.installExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:6762)","    at async O.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)"]
[2022-02-28 14:30:00.987] [renderer3] [error] Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17874
    at Array.reduce (<anonymous>)
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17860)
    at O.joinAllSettled (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9049)
    at async O.installExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:6762)
    at async O.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)
[2022-02-28 14:30:42.243] [renderer3] [error] Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.: Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.
    at w.toConfigurationEditingError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1896:12622)
    at w.updateConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1896:9708)
    at w.doWriteConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1896:9554)`

Screenshots: Output log of Error Message:
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/11457837/156108036-d1418b90-1880-48b5-be02-b5c4dafc03c8.png">

Let me know if you need any other informations.

**Comment by jag-sfdc** [comment]
@saurabhsoodsfdc - Have you tried both downloading vsix files and running "Install from VSIX" and also by "Searching Extensions in Marketplace" from "Extensions" side bar? Do both give you the same error?

**Comment by satish151994** [comment]
when am installing the salesforce extension pack getting the below error
end of central directory record signature not found,end of central directory record signature not found: Error: end of central directory record signature not found,end of central directory record signature not found

**Comment by sfsagar** [comment]
![Screenshot 2023-12-27 031443](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/ba9a0957-87d6-4eeb-9987-c89c8c0d89ee)
Extension pack not able to install
![Screenshot 2023-12-27 034204](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/96bff193-e4a7-4bcc-a702-1abff88c90ff)
