### ISSUE TITLE
Org Browser - retrieve or metadata is not working

### ISSUE THREAD

**Issue by SimonaIstrate31** [forcedotcom/salesforcedx-vscode#4008]
Summary
When using the OrgBrowser tool in VS Code, the following error occurs:

SyntaxError: Unexpected token c in JSON at position 4

Steps To Reproduce:
Go to OrgBrowser while in a Repo in VS Code
Refresh

Expected result
OrgBrowser should have pulled the data from my org

Actual result
SyntaxError: Unexpected token c in JSON at position 4

sfdx-project.json file:

{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://test.salesforce.com",
  "sourceApiVersion": "54.0"
}

**Comment by floralan** [comment]
Hi @SimonaIstrate31 , can you share what version of the Salesforce Extensions you're using? This can be found by searching for 'Salesforce' from the Marketplace tab on the left sidebar.

**Comment by marine-marsella** [comment]
Hi, 
I've the same issue 😖 with my visual studio on my mac (macOs 12.4)
my salesforce extension pack is in version 55.0.0 
my sfdx-project.json is in version 55.0 too, and looks like this : 
```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://test.salesforce.com",
  "sourceApiVersion": "55.0"
}
```
Thanks for your help

**Comment by pnoges-clarusgroup-com** [comment]
I get an error that looks somewhat similar, whenever I try to use the OrgBrowser:

```
SyntaxError: Unexpected token S in JSON at position 0
	at eh (c:\Users\*******\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.3.0\dist\index.js:139:34248)
	at ei.getTypes (c:\Users\*******\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.3.0\dist\index.js:139:33402)
	at async ei.getChildren (c:\Users\*******\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.3.0\dist\index.js:139:33003)
	at async b.R (c:\Users\*******\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:18944)
	at async b.getChildren (c:\Users\*******\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:15363)
```
