### ISSUE TITLE
ERROR running force:source:push: Push failed.

### ISSUE THREAD

**Issue by prasadnikam-merce** [forcedotcom/salesforcedx-vscode#4084]
[12:18:50] 'sfdx-push' errored after 22 min
[12:18:50] Error: Push failed:

at C:\Users\Lenovo\Documents\FDB Workspace\fdb\scripts\sfdx\sfdx.js:105:10
at sfdx-push (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\undertaker\lib\set-task.js:13:15)
at bound (domain.js:430:14)
at runBound (domain.js:443:12)
at asyncRunner (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\async-done\index.js:55:18)
at processTicksAndRejections (internal/process/task_queues.js:75:11)
[12:18:50] 'push-all' errored after 22 min
events.js:292
throw er; // Unhandled 'error' event
^

Error: spawn gulp ENOENT
at notFoundError (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\cross-spawn\lib\enoent.js:6:26)
at verifyENOENT (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\cross-spawn\lib\enoent.js:40:16)
at ChildProcess.cp.emit (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\cross-spawn\lib\enoent.js:27:25)
at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
at ChildProcess.cp.emit (C:\Users\Lenovo\Documents\FDB Workspace\fdb\node_modules\cross-spawn\lib\enoent.js:30:37)
at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn gulp',
path: 'gulp',
spawnargs: [
'push-all',
'--siteadmin=',
'--domain=',
'--urlprefix=',
'--org=',
'--static_domain='
]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by randi274** [comment]
Hi @prasadnikam-merce can you try running the following SFDX command directly? `sfdx force:source:push`
