### ISSUE TITLE
Salesforce org connection failing

### ISSUE THREAD

**Issue by mattd624** [forcedotcom/salesforcedx-vscode#4313]
When I open a folder in VS Code, my connections to salesforce orgs fail. On the blue bar at the bottom, I have 0, 0 No error messages appear. I have no cloud icon for the "salesforce explorer", and no salesforce org commands (like Authorize an Org, Open Default Org, etc.) when I do Ctrl+Shift+P. Sometimes eventually it will come up, but I can't tell why or what I might have done to make it start working.  It seems random. Known issue? 

I have tried restarting the software, doing an extensions refresh, explorer refresh, etc. I cannot figure out what will make the connection appear. It just seems to do it when it wants. 

No error messages:
![image](https://user-images.githubusercontent.com/31457474/180571360-53c5c53e-4a15-42fd-b6f5-6eb3fc0b44ed.png)

No org commands:
![image](https://user-images.githubusercontent.com/31457474/180571445-8cde15e9-f005-4181-990c-f739bb215f89.png)

Icons missing:
![image](https://user-images.githubusercontent.com/31457474/180571742-99de2b1e-0178-4d85-b0f2-fc2f847aa3e9.png)

**Comment by randi274** [comment]
Hi @mattd624 - what system are you running on? Sometimes fully re-installing VS Code will also do the trick!

**Comment by mattd624** [comment]
I reopened a folder that was working before, and it took a few minutes but it eventually loaded these items, and in the OUTPUT section, it gave me this, which hopefully helps: 

[Error - 3:26:36 PM] [object Object]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ComponentIndexer.loadTagsFromIndex (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\@salesforce\lwc-language-server\lib\component-indexer.js:109:36)
    at ComponentIndexer.init (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\@salesforce\lwc-language-server\lib\component-indexer.js:135:14)
    at Server.onInitialize (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\@salesforce\lwc-language-server\lib\lwc-server.js:66:31)
    at c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\vscode-languageserver\lib\main.js:822:26
    at handleRequest (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\vscode-jsonrpc\lib\main.js:367:27)
    at processMessageQueue (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\vscode-jsonrpc\lib\main.js:257:17)
    at Immediate._onImmediate (c:\Users\mdavis\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-55.6.0\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at processImmediate (node:internal/timers:464:21)

**Comment by mattd624** [comment]
Windows 10 on both home and the office machines, and the same thing happens
on both machines. Are we talking reinstall with fresh default settings?

**Comment by mattd624** [comment]
Maybe I will try the system installer instead of user installer this time.

**Comment by mattd624** [comment]
Reinstalling did not work. At work I updated the sfdx cli to 7.160.0 and it
didn't fix it, but I am updating it at home now.

**Comment by mattd624** [comment]
Also when I do >Refresh Components, I get this:
[image: image.png]

**Comment by mattd624** [comment]
https://developer.salesforce.com/tools/vscode/en/troubleshooting

This site helped me figure it out. I believe this problem was because I was
opening the project in a folder that was not a top level folder. It was one
below.

I was opening this one:
[image: image.png]
When I opened the one above it, it worked! That was a lot of
troubleshooting!


On my work computer it was that, AND that I was running jdk18! Once I
opened the right folder, I finally got an error message about having an
unsupported version of java.

**Comment by randi274** [comment]
Wooo awesome @mattd624! Glad to hear you were able to get it sorted, and that our documentation site was of help to you too. We've got lots of great documentation there on all the extension features, as well as several trails like [this one](https://trailhead.salesforce.com/en/content/learn/trails/set-up-your-workspace-and-install-developer-tools) over on Trailhead.
