### ISSUE TITLE
LWC and Aura apps Crash on load, SFDX can't deploy

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/salesforcedx-vscode#4358]
I get a "connection is closed." error from the aura app. The following is the output of its error message. The LWC app crashes enough that VS Code throws an error and refuses to restart it. I have tried numerous recent version of all mentioned apps, none fix the issue.

However, the most concerning issue is SFDX can't deploy to the org. Internet is fine and I've tried re-authorizing. Doesn't help. It does not throw an error when it fails, it simply returns a completion/error message: "Deploy Errors 00:16:10.745 ended SFDX: Deploy Source to Org"

Here is the error thrown by the Aura app:

Error: UNKNOWN: unknown error, lstat 'c:/Users/PATH_REPLACED'
    at lstatSync (node:fs:1514:3)
    at Object.e.lstatSync (node:electron/js2c/asar_bundle:5:3752)
    at Object.read (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.stat\out\providers\sync.js:5:31)
    at Object.statSync (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.stat\out\index.js:18:17)
    at c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.scandir\out\providers\sync.js:42:30
    at Array.map (<anonymous>)
    at readdir (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.scandir\out\providers\sync.js:40:18)
    at Object.read (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.scandir\out\providers\sync.js:12:12)
    at SyncReader.scandirSync [as _scandir] (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.scandir\out\index.js:18:17)
    at SyncReader._handleDirectory (c:\Users\...\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.15.0\node_modules\@nodelib\fs.walk\out\readers\sync.js:28:34) {
  errno: -4094,
  syscall: 'lstat',
  code: 'UNKNOWN',
  path: 'c:/Users/PATH_REPLACED'

**Comment by NuAgeDan** [comment]
It appears the file mentioned in the PATH_REPLACED portion does not exist. It is possible it was deleted by another user, was not pulled down with a refresh and thus the system is looking for something which doesn't exist. 

The file is an aura file. This might be the cause of the Aura issue but really shouldn't break deploy or LWC functionality

**Comment by jeffb-sfdc** [comment]
@NuAgeDan What are the steps needed to reproduce this issue?
