### ISSUE TITLE
How do I run the lang server locally ?

### ISSUE THREAD

**Issue by jayonsoftware** [forcedotcom/salesforcedx-vscode#45]
Kind of stupid question. Is apex-jorje-lsp.jar the apex lang server? 

Thx

Jay

**Comment by guw** [comment]
Yes. It's the APEX language server.

**Comment by vazexqi** [comment]
@jayonsoftware Take a look at https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/src/languageServer.ts on how to start the server. Currently, it uses local sockets. There is an issue (#4) to change this to use stdio/stdout.

**Comment by jayonsoftware** [comment]
Cant we start it with out typescript, some thing like 

`java -jar apex.jar apex.jorje.lsp.ApexLanguageServerLauncher -apex-lsp.port 8888` ...this is did not work

Jay

**Comment by vazexqi** [comment]
You can certainly start it outside of TypeScript. The way it works is that it requires the port that you pass to it using -Dapex-lsp.port to be listening by the time it is started.

**Comment by jayonsoftware** [comment]
Still having no luck...

`C:\Dev>java -jar apex.jar apex.jorje.lsp.ApexLanguageServerLauncher -Dapex-lsp.port 88
Exception in thread "main" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at apex.jorje.lsp.impl.connection.SocketStreamProvider.initialize(SocketStreamProvider.java:52)
        at apex.jorje.lsp.ApexLanguageServerLauncher.launch(ApexLanguageServerLauncher.java:74)
        at apex.jorje.lsp.ApexLanguageServerLauncher.main(ApexLanguageServerLauncher.java:63)`

**Comment by vazexqi** [comment]
@jayonsoftware You are not sending the commands in the right order. See the languageServer.ts file to see the order. You cannot have `-Dapex-lsp.port 88` at the end.

```
# Here I actually have something running on port 8000
nchen@nchen-wsm1:~/Development/Node/salesforcedx-vscode/packages/salesforcedx-vscode-apex/out|⇒  java -cp apex-jorje-lsp.jar -Dapex-lsp.port=8000 -Dapex.lsp.root.log.level=ALL apex.jorje.lsp.ApexLanguageServerLauncher                                ± develop ✔ 14:16:54
14:16:55.417 [main] INFO  a.j.l.i.c.SocketStreamProvider - Connecting to socket on localhost:8000
14:16:55.482 [main] INFO  a.j.lsp.ApexLanguageServerLauncher - Starting Apex Language Server Protocol
^C%                                                                               

# Here I don't have anything running on port 1234
nchen@nchen-wsm1:~/Development/Node/salesforcedx-vscode/packages/salesforcedx-vscode-apex/out|⇒  java -cp apex-jorje-lsp.jar -Dapex-lsp.port=1234 -Dapex.lsp.root.log.level=ALL apex.jorje.lsp.ApexLanguageServerLauncher                                ± develop ✔ 14:17:29
14:17:31.644 [main] INFO  a.j.l.i.c.SocketStreamProvider - Connecting to socket on localhost:1234
Exception in thread "main" java.lang.RuntimeException: Launch with -Dapex-lsp.port=somePort to connect to the server.
	at apex.jorje.lsp.impl.connection.SocketStreamProvider.initialize(SocketStreamProvider.java:54)
	at apex.jorje.lsp.ApexLanguageServerLauncher.launch(ApexLanguageServerLauncher.java:74)
	at apex.jorje.lsp.ApexLanguageServerLauncher.main(ApexLanguageServerLauncher.java:63)
```

**Comment by jayonsoftware** [comment]
I am still new to LSP and also to TS. 

I am assuming apex-jorje-lsp.jar is the APEX server VS code connects too ? So why can't I start the server in standalone mode with out typescript. For example the follwing is not working, all i want to do is start the LSP and then send Json-RPC commands from my c# app to test some of the functions of the APEX LSP. 

`C:\Dev>java -cp apex-jorje-lsp.jar -Dapex-lsp.port=9999 -Dapex.lsp.root.log.level=ALL apex.jorje.lsp.ApexLanguageServerL
auncher
17:52:47.232 [main] INFO  a.j.l.i.c.SocketStreamProvider - Connecting to socket on localhost:9999
Exception in thread "main" java.lang.RuntimeException: Launch with -Dapex-lsp.port=somePort to connect to the server.
        at apex.jorje.lsp.impl.connection.SocketStreamProvider.initialize(SocketStreamProvider.java:54)
        at apex.jorje.lsp.ApexLanguageServerLauncher.launch(ApexLanguageServerLauncher.java:74)
        at apex.jorje.lsp.ApexLanguageServerLauncher.main(ApexLanguageServerLauncher.java:63)`

**Comment by vazexqi** [comment]
Just to be clear, this has _nothing_ to do with TypeScript. We are using this same language server from a Java client (Eclipse).

The issue you are having has to do with _our_ current particular implementation choice of using a socket to connect. That is why it requires the rigmarole you see in languageServer.ts right now.

When I implement #4 you should be able to interact with it using stdin/stdout.

So you can either wait for that to be implemented, or start a socket from your C# implementation and send commands to/from there.
