### ISSUE TITLE
Apex Language Service crashes with null pointer exception

### ISSUE THREAD

**Issue by rob-baillie-ortoo** [forcedotcom/salesforcedx-vscode#4500]
### Summary

Occassionally, and unclear when or how it happens, I'm getting a full crash of Apex Language Server that results in the complete loss of auto-complete / snippets / run-test button functionality.

Only a restart of VSCode corrects the issue.

### Steps To Reproduce:

Unsure how to reproduce, but the Apex Language Server outputs the following errors...

```
Oct 14, 2022 11:07:46 AM apex.jorje.semantic.compiler.CodeUnit additionalValidate
INFO: unexpected error during apex additional validate:
Class body hit character limit 10000 @isTest

// code output removed

java.lang.NullPointerException
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression$NameValueParameter.getSObjectField(NewKeyValueObjectExpression.java:223)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.lambda$visitEnd$0(SObjectCompletionActivationStrategy.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:133)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy$ContextDeterminer.visitEnd(SObjectCompletionActivationStrategy.java:78)
	at apex.jorje.semantic.ast.expression.NewKeyValueObjectExpression.traverse(NewKeyValueObjectExpression.java:95)
	at apex.jorje.semantic.ast.statement.VariableDeclaration.traverse(VariableDeclaration.java:81)
	at apex.jorje.semantic.ast.statement.VariableDeclarationStatements.traverse(VariableDeclarationStatements.java:87)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.compiler.CodeUnit.additionalValidate(CodeUnit.java:270)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:178)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:97)
	at apex.jorje.lsp.impl.completions.SObjectCompletionActivationStrategy.analyze(SObjectCompletionActivationStrategy.java:66)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.constructorContext(ConstructorContextUtil.java:64)
	at apex.jorje.lsp.impl.utils.ConstructorContextUtil.isConstructorContext(ConstructorContextUtil.java:51)
	at apex.jorje.lsp.impl.completions.SystemNamespaceCompletionStrategy.lambda$provideCompletions$1(SystemNamespaceCompletionStrategy.java:79)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.completions.SystemNamespaceCompletionStrategy.provideCompletions(SystemNamespaceCompletionStrategy.java:76)
	at apex.jorje.lsp.impl.completions.ApexCompletionStrategyAggregator.provideCompletions(ApexCompletionStrategyAggregator.java:101)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$completion$0(StandardTextDocumentService.java:126)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Salesforce Extension Version in VS Code**:  Salesforce Extension Pack - 55.8.0

**SFDX CLI Version**: sfdx-cli/7.169.1 darwin-x64 node-v16.17.0

**OS and version**: macOS Big Sur, 11.5.2

**Comment by gbockus-sf** [comment]
Thanks for the report @rob-baillie-ortoo I was able to track down the code where this error was occurring, but didn't see anything obvious that would result in the NPE.  I tagged this as a bug so an internal ticket would be created and prioritized.  We'll need to dig into the apex language server to get to the bottom of it.

**Comment by rob-baillie-ortoo** [comment]
Thanks.  If I find the Apex that triggers this issue I'll update the ticket, obviously.

**Comment by diyer** [comment]
Closing this old bug. Please create a new issue if the problem persists with our lates vs code extensions version that has many more enhancements since this bug was logged. Thank you!
