### ISSUE TITLE
causes extension host to restart repeatedly.

### ISSUE THREAD

**Issue by codefriar** [forcedotcom/salesforcedx-vscode#4908]
Type: <b>Bug</b>

just having it installed causes the extension host to restart continuously. 

Extension version: 58.0.1
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|23, 48, 34|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by codefriar** [comment]
found some more details in the extension host log: 
```
2023-06-05 12:45:00.054 [error] RuntimeError: abort(Error: No default org is set. Run "SFDX: Create a Default Scratch Org" or "SFDX: Authorize an Org" to set one.). Build with -s ASSERTIONS=1 for more info.
    at process.wA (/Users/kpoorman/.vscode/extensions/petli-full.jq-vscode-0.1.3/dist/extension.js:2:1135641)
    at process.emit (node:events:525:35)
    at process.length (/Users/kpoorman/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.5864/extension.js:394:51519)
    at process.on.process.emit (/Users/kpoorman/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/extension/dist/webpack:/auto-rename-tag/node_modules/source-map-support/source-map-support.js:617:24)
    at process.on.process.emit (/Users/kpoorman/.vscode/extensions/zignd.html-css-class-completion-1.20.0/dist/extension.js:2:802330)
    at process.on.process.emit (/Users/kpoorman/.vscode/extensions/github.copilot-1.88.132/dist/extension.js:8:743186)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

```

**Comment by codefriar** [comment]
I have confirmed that this issue goes away when I designate a default org. I actually now believe this fails because i've also set the enable-sobject-refresh-on-startup to true. When a default org is not specified the refresh fails and causes the extension host to die as seen in the logs above.

**Comment by CristiCanizales** [comment]
Hi @codefriar ! Thanks for logging this. I couldn't get that error but a different one where it kept trying to refresh forever. We should need to verify if there's a default org set before executing the refresh. I've tagged this as a bug so it's added to our backlog. Let me know if you need help with anything else.

**Comment by diyer** [comment]
Closing this old bug with old version of extension. Please file a new bug with our latest extensions if the problem persists. Thank you!
