### ISSUE TITLE
The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by samwolfe-stripe** [forcedotcom/salesforcedx-vscode#4994]
### Summary

When the LWC Language Server attempts to start, it crashes 5 times immediately and no longer tries to restart

### Steps To Reproduce:

1.  Open an LWC test file
2. After a few moments, VSCode will display the message "The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

### Expected result

The LWC Language Server should not crash

### Actual result

The LWC Language Server crashes
<img width="465" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/95635953/5084d0ea-3ed7-4bc0-8e71-30ac1159c389">

### Additional information

**Error output**
```
TypeError: Cannot read properties of undefined (reading 'location')
    at mapLwcMetadataToInternal (/Users/user/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-58.7.1/node_modules/@salesforce/lwc-language-server/lib/javascript/type-mapping.js:428:188)
    at compileSource (/Users/user/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-58.7.1/node_modules/@salesforce/lwc-language-server/lib/javascript/compiler.js:172:66)
    at compileDocument (/Users/user/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-58.7.1/node_modules/@salesforce/lwc-language-server/lib/javascript/compiler.js:184:12)
    at Server.onDidChangeContent (/Users/user/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-58.7.1/node_modules/@salesforce/lwc-language-server/lib/lwc-server.js:195:84)
[Error - 12:12:50 PM] Connection to server got closed. Server will not be restarted.

/Users/user/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-58.7.1/node_modules/@salesforce/lwc-language-server/lib/javascript/type-mapping.js:428
    const declarationLoc = externalToInternalLoc((_a = defaultExport === null || defaultExport === void 0 ? void 0 : defaultExport.location) !== null && _a !== void 0 ? _a : mainClassObj.location);
                                                                                                                                                                                           ^
```

**Other Steps Tried**
- Restarted VSCode
- Uninstalled and Reinstalled Extension Pack
- Restarted machine
- Uninstalled and Reinstalled SF CLI 

**Salesforce Extension Version in VS Code**:

- Salesforce Extension Pack (Expanded) v58.7.1
- Lightning Web Components v58.7.1

**SFDX CLI Version**:

- `sf --version` => `@salesforce/cli/2.1.7 darwin-arm64 node-v18.15.0`

**OS and version**:

Mac OS Ventura 13.4.1 (c) (M1)

**Comment by samwolfe-stripe** [comment]
Likely related to https://github.com/forcedotcom/lightning-language-server/pull/570 which is 1: the most recent update to the LWC language server and 2: introduced the function which is failing `mapLwcMetadataToInternal `

**Comment by CristiCanizales** [comment]
Hello! Thank you all for bringing this to our attention. We'll be taking a look at it!

**Comment by divmain** [comment]
@samuel-pipelaunch @samwolfe-stripe this looks like a relatively easy fix, apologies for the issue. Do you happen to have a minimal repro that causes this issue? Rather than throwing code over the wall, I'd like to confirm that the fix will address the issue you're experiencing, if possible. If you don't have a minimal repro, it'd be great if you could manually verify after we push out a fix.

**Comment by samwolfe-stripe** [comment]
@divmain Thanks for taking a look, I tried to set up a minimal repo but couldn't actually trigger the LWC Language Server to run (not sure what actually causes it to kick off), so unfortunately can only replicate in my local repo.

Happy to verify a fix manually

**Comment by codythomaszeitler** [comment]
I made a fix within the lightning-language-server repository. 
https://github.com/forcedotcom/lightning-language-server/pull/577

To reproduce the problem, just make an LWC, and remove the default export and put something else in.

```export class TestClass {
  get a() {
    return "a";
  }

  b = "b";
}```

This should cause the server to crash.

**Comment by codythomaszeitler** [comment]
@samuel-pipelaunch Okay, I got the exact error that you mentioned above (minus the version number).

I reproduced it in the following manner:

Create a brand sfdx project:  
1) sf project generate --projectname crashme
2) cd crashme
3) code . (open up vscode in the current directory)
4) Wait for all of the extensions to start 
5) Run the following command in vscode: SFDX: Create a Lightning Web Component
6) Call the LWC "crashMe".

`
import { LightningElement } from 'lwc';
export default class CrashMe extends LightningElement {}
`

You'll have something like this.

Replace it with this:
`
export function add(a, b) {
    return a + b;
}
`

You will start to see the exception in  your "LWC Language Server" output in vscode:

`
c:\Users\Cody\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.9.1\node_modules\@salesforce\lwc-language-server\lib\javascript\type-mapping.js:429
    const declarationLoc = externalToInternalLoc((_a = defaultExport === null || defaultExport === void 0 ? void 0 : defaultExport.location) !== null && _a !== void 0 ? _a : mainClassObj.location);
                                                                                                                                                                                           ^

TypeError: Cannot read properties of undefined (reading 'location')
    at mapLwcMetadataToInternal (c:\Users\Cody\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.9.1\node_modules\@salesforce\lwc-language-server\lib\javascript\type-mapping.js:429:188)
    at compileSource (c:\Users\Cody\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.9.1\node_modules\@salesforce\lwc-language-server\lib\javascript\compiler.js:172:66)
    at compileDocument (c:\Users\Cody\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.9.1\node_modules\@salesforce\lwc-language-server\lib\javascript\compiler.js:184:12)
    at Server.onDidChangeContent (c:\Users\Cody\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.9.1\node_modules\@salesforce\lwc-language-server\lib\lwc-server.js:195:84)

`

**Comment by codythomaszeitler** [comment]
@samuel-pipelaunch The reason that it is failing is since the file cannot find a "default export". In this specific scenario, the file also has no classes, which let's it get to the error that you found. The error from what I posted is when there is at least one class in the file.

**Comment by msuchy96** [comment]
I have the same issue with following stacktrace: 
```
c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\sax\lib\sax.js:652
    er = new Error(er)
         ^

Error: Invalid character in entity name
Line: 569
Column: 214
Char: =
    at error (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\sax\lib\sax.js:652:10)
    at strictFail (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\sax\lib\sax.js:678:7)
    at SAXParser.write (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\sax\lib\sax.js:1499:13)
    at exports.Parser.Parser.parseString (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\xml2js\lib\parser.js:5:59)
    at Typing.declarationsFromCustomLabels (c:\Users\msuch\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-60.5.1\node_modules\@salesforce\lwc-language-server\lib\typing.js:68:47)

Node.js v18.17.1
[Error - 11:48:39 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by ministe2003** [comment]
I've recently started getting this issue. I've tried completely uninstalling sf, vscode, java, node and npm. When I go through the process of reinstalling it comes back once I install the extended extension pack

Name: Salesforce Extension Pack (Expanded)
Id: salesforce.salesforcedx-vscode-expanded
Description: Extensions for developing on the Salesforce Platform
Version: 61.10.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-expanded

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Java:
C:\Program Files\Eclipse Adoptium\jdk-21.0.4.7-hotspot\bin\java.exe

sf:
@salesforce/cli: Updating CLI... already on version 2.55.6-648ad30

```
c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Invalid character in entity name
Line: 18656
Column: 37
Char:  
    at error (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:684:7)
    at SAXParser.write (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:1522:13)
    at exports.Parser.Parser.parseString (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:5:59)
    at Typing.declarationsFromCustomLabels (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\@salesforce\lwc-language-server\lib\typing.js:68:47)

Node.js v20.14.0
[Error - 11:16:37 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by jean-feng** [comment]
I got a new C driver, installed new Windows:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎9/‎6/‎2024
OS build	19045.4894
Experience	Windows Feature Experience Pack 1000.19060.1000.0

Then I installed sf @salesforce/cli/2.58.7 win32-x64 node-v20.17.0

Visual Studio Code 
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Once I installed Salesforce Extension Pack
v61.12.0

I got The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:25:57 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:26:09 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:26:21 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:26:33 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Error - 10:26:44 AM] Connection to server got closed. Server will not be restarted.

**Comment by peternhale** [comment]
@jean-feng would you mind opening a new issue. Thank you.

**Comment by jean-feng** [comment]
@peternhale https://github.com/forcedotcom/salesforcedx-vscode/issues/5869 is created
