### ISSUE TITLE
Salesforce Debugger for VSCode

### ISSUE THREAD

**Issue by zanon1101** [forcedotcom/salesforcedx-vscode#5063]
### Summary

_Short summary of what is going on or to provide context_.

I updated to sf CLI v2 today (unsure if related) per these instructions:

https://developer.salesforce.com/docs/atlas.en-us.244.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

When setting a breakpoint and or checkpoint and running **ctrl + cmd + p -> Update checkpoints in Org** I get the error:
**There is no line breakpoint information for the current project**.

I've tried: 

- reinstalling all the VSCode extensions
-  re-authing my org
-  checking Apex Language Server is running
- Restarting VSCode
- Restarting computer

### Steps To Reproduce:

1.  Open VSCode
2. Set a breakpoint (right clicking in class next to the line number) on a valid line of code 
3. Deploy source to org (right click command - this deploys the class to org sucessfully)
4. cmd + ctrl + p -> Update checkpoints in org
5. ERROR

Similar issue if i click 'Debug Test' on the test class in VSCode I get the pop 'Apex language server could not provide information about valid breakpoints. (Screenshot attached) and log output:

`2613: launchRequest: args={"name":"Launch Apex Replay Debugger","type":"apex-replay","request":"launch","logFile":"/Users/elliottfuller/MyConnect/myconnect-sf/.sfdx/tools/debug/logs/07L8s000008IvL0EAK.log","stopOnEntry":false,"trace":true,"projectPath":"/Users/elliottfuller/MyConnect/myconnect-sf","lineBreakpointInfo":null,"__sessionId":"39efe19a-fd8d-46b4-a7f1-06648a7dbca6"}`

I can see lineBreakpointinfo:"null" which I assume is the cause

### Expected result
Checkpoints / breakpoints are updated and debugger runs the test code

_Describe what should have happened_.
checkpoints are set and debugger runs

### Actual result

`Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
Checkpoints can be set on a valid line of Apex source. Invalid checkpoint location: URI=file:///Users/elliottfuller/MyConnect/myconnect-sf/packages/myconnect/main/default/classes/OpportunityHelperTest.cls, Line=1041
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.
14:33:28.572 ended Debug Test(s)`

_Describe what actually happened instead_.
Error is logged in the console

### Additional information
<img width="513" alt="Screen Shot 2023-08-31 at 2 43 15 pm" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/47850054/df21d98b-6d50-4927-b13
<img width="1371" alt="Screen Shot 2023-08-31 at 2 43 37 pm" src
<img width="376" alt="Screen Shot 2023-08-31 at 2 46 48 pm" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/47850054/a4ed6e8c-538e-4b01-a453-5cd208642911">
="https://github.com/forcedotcom/salesforcedx-vscode/assets/47850054/5b106a8f-a048-4ec5-97d0-38fc773096f3">
e-7124735161e3">

_Feel free to attach a screenshot_.
<img width="433" alt="Screen Shot 2023-08-31 at 2 43 56 pm" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/47850054/f6524c3b-3681-48c1-a262-5a141f54b033">

**Salesforce Extension Version in VS Code**:
v58.13.1

**SFDX CLI Version**:
@salesforce/cli/2.6.7 darwin-arm64 node-v16.15.1

**OS and version**:
macOS Monterery - Version: 12.5.1

**Comment by peternhale** [comment]
@zanon1101  The error you are seeing makes me think that there is an issue with the apex extension. The message is displayed when the apex replay debugger cannot get a reference to the extension via vscode api.

Would you please check the running extensions Command pallet `Developer: Show Running Extensions` and check if `Apex 58.13.1` has activated.

If it has activated, check the `Apex language Server` output to see if there are an errors displayed.

**Comment by zanon1101** [comment]
I've tried reinstalling all the salesforce extensions, i've never really looked at the output of the apex language server in vscode but i can see there is something going on that could be an issue. Where it says 'method already defined' 'clone' on SuubmissionModel.SuccessModel... we aren't even using clone on that class anywhere

`09:52:35.025 [ForkJoinPool.commonPool-worker-5] ERROR a.j.l.i.c.CodeLensesProviderAggregator - Encountered an error with code lens provider apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider@65f87a2c
java.lang.IllegalStateException: Method already defined: clone SubmissionModel.SuccessModel SubmissionModel.SuccessModel.clone() from the type SubmissionModel.SuccessModel
	at apex.common.base.Result.throwIfError(Result.java:112)
	at apex.jorje.semantic.symbol.member.method.MethodTableFactory.newMethodTable(MethodTableFactory.java:44)
	at apex.jorje.semantic.symbol.member.method.MethodTableFactory.newMethodTable(MethodTableFactory.java:39)
	at apex.jorje.lsp.impl.index.symbol.VirtualMethodTableInitializer.get(VirtualMethodTableInitializer.java:75)
	at apex.jorje.lsp.impl.index.symbol.VirtualMethodTableInitializer.get(VirtualMethodTableInitializer.java:40)
	at apex.common.base.Initializers$MemoizingInitializer.get(Initializers.java:74)
	at apex.jorje.semantic.symbol.type.AbstractTypeInfo.methods(AbstractTypeInfo.java:122)
	at apex.jorje.semantic.ast.compilation.VirtualMethodsCreator.create(VirtualMethodsCreator.java:117)
	at apex.jorje.lsp.impl.index.symbol.VirtualStandardTypeInfo$Builder.build(VirtualStandardTypeInfo.java:197)
	at apex.jorje.lsp.impl.index.symbol.VirtualStandardTypeInfo$Builder.build(VirtualStandardTypeInfo.java:125)
	at apex.jorje.semantic.symbol.type.AbstractTypeInfo$Builder.buildResolved(AbstractTypeInfo.java:213)
	at apex.jorje.lsp.impl.symbols.ApexSymbolProvider.find(ApexSymbolProvider.java:130)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.find(StandardSymbolResolver.java:448)
	at apex.jorje.semantic.symbol.resolver.rules.TwoPartTypeNameResolveRules$InnerTypeInSameNamespace.lookup(TwoPartTypeNameResolveRules.java:280)
	at apex.jorje.semantic.symbol.resolver.rules.TypeNameResolutionOrderUtil.getTypeFromTwoPartRules(TypeNameResolutionOrderUtil.java:130)
	at apex.jorje.semantic.symbol.resolver.rules.TypeNameResolutionOrderUtil.bindToType(TypeNameResolutionOrderUtil.java:62)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupTypeInfo(StandardSymbolResolver.java:394)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupTypeInfoIdentifiers(StandardSymbolResolver.java:199)
	at apex.jorje.semantic.symbol.resolver.TypeRefResolvers$ClassTypeResolver.resolve(TypeRefResolvers.java:148)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupTypeInfo(StandardSymbolResolver.java:161)
	at apex.jorje.semantic.ast.statement.VariableDeclarationStatements.resolveType(VariableDeclarationStatements.java:171)
	at apex.jorje.semantic.ast.visitor.PostTypeResolveVisitor.visit(PostTypeResolveVisitor.java:160)
	at apex.jorje.semantic.ast.visitor.PostTypeResolveVisitor.visit(PostTypeResolveVisitor.java:56)
	at apex.jorje.semantic.ast.statement.VariableDeclarationStatements.traverse(VariableDeclarationStatements.java:84)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.compiler.CodeUnit.traverse(CodeUnit.java:195)
	at apex.jorje.semantic.compiler.CompilerOperations$PostTypeResolveOperation.invoke(CompilerOperations.java:84)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processFirstStage(CompilerStageProcessor.java:136)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processToStage(CompilerStageProcessor.java:105)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:120)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:149)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:236)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:99)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.lambda$provideCodeLenses$0(ApexTestRunCodeLensesProvider.java:116)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.provideCodeLenses(ApexTestRunCodeLensesProvider.java:115)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.lambda$provideCodeLenses$0(CodeLensesProviderAggregator.java:58)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.provideCodeLenses(CodeLensesProviderAggregator.java:56)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeLens$9(StandardTextDocumentService.java:280)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

**Comment by zanon1101** [comment]
FIXED:

I think it was an issue with local repo metadata being corrupt or out of sync or something. I deleted my local sf repo and cloned again from bitbucket and voila it works.

**Comment by CristiCanizales** [comment]
Hi @zanon1101, I'm glad you were able to solve your problem. I'll be closing this issue then.
