### ISSUE TITLE
Crash of Apex Indexer on initialisation

### ISSUE THREAD

**Issue by rob-baillie-ortoo** [forcedotcom/salesforcedx-vscode#5100]
### Summary

Apex Indexing is failing on start-up, disabling most capabilities of the extension in the editor.

### Steps To Reproduce:
1. Open a VSCode Salesforce project
2. Open Apex Language Server output
3. See error

### Expected result
1. Be able to command+click navigate to method definitions
2. Be able to use 'Run Test' editor commands
3. Be able to use auto-complete

### Actual result

```
09:28:22.400 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
09:28:22.459 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in Apex types.
09:28:22.480 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Collecting built-in standard types from jar
Sep 18, 2023 9:28:23 AM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 29 ms.
09:28:24.379 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done collecting built-in standard types from jar
09:28:24.379 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning Apex Standard Library.
09:28:25.806 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done scanning Apex Standard Library.
09:28:25.819 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Starting ApexIndexer.
09:28:25.848 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Start indexer.
09:28:25.872 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 3450 ms.
09:28:25.897 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
09:28:25.899 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning workspace source.
09:28:26.155 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Loading existing resource files from apex.db.
09:28:26.212 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Building change list.
09:28:26.309 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Applying found changes
09:28:26.311 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Updating 35 Apex artifacts in Apex DB
09:28:26.330 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Error during startup
org.eclipse.jdt.internal.core.nd.db.IndexException: Attempted to free more memory from pool 265 than was ever allocated
	at org.eclipse.jdt.internal.core.nd.db.MemoryStats.recordFree(MemoryStats.java:221)
	at org.eclipse.jdt.internal.core.nd.db.Database.free(Database.java:1066)
	at org.eclipse.jdt.internal.core.nd.Nd.deleteIfUnreferenced(Nd.java:639)
	at org.eclipse.jdt.internal.core.nd.Nd.processDeletions(Nd.java:164)
	at org.eclipse.jdt.internal.core.nd.Nd.releaseWriteLock(Nd.java:357)
	at org.eclipse.jdt.internal.core.nd.Nd.releaseWriteLock(Nd.java:342)
	at apex.jorje.lsp.impl.index.ApexIndexer.deleteTypeInfo(ApexIndexer.java:1024)
	at apex.jorje.lsp.impl.index.ApexIndexer.buildCache(ApexIndexer.java:246)
	at apex.jorje.lsp.impl.index.ApexIndexer.lambda$startUp$1(ApexIndexer.java:803)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.index.ApexIndexer.startUp(ApexIndexer.java:801)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:230)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Additional information

**Salesforce Extension Version in VS Code**: v58.14.2
**SFDX CLI Version**:  @salesforce/cli/2.7.11 darwin-arm64 node-v18.17.1
**OS and version**: macOs Ventura 13.5.2 (22G91)

**Comment by rob-baillie-ortoo** [comment]
Was previously running JAVA temurin-11.jdk (stated as supported Java version).

Upgrade to Java JDK 17.0.8 and early signs suggest that this issue may have resolved.

However, now getting a different error, which I guess may be related:

```
09:53:46.997 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
09:53:47.003 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in Apex types.
09:53:47.004 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Collecting built-in standard types from jar
09:53:47.327 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done collecting built-in standard types from jar
09:53:47.327 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning Apex Standard Library.
09:53:47.482 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done scanning Apex Standard Library.
09:53:47.484 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Starting ApexIndexer.
09:53:47.490 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 492 ms.
09:53:47.492 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Start indexer.
09:53:47.499 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
09:53:47.499 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning workspace source.
09:53:47.555 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Loading existing resource files from apex.db.
09:53:47.614 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Building change list.
09:53:47.724 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Applying found changes
09:53:47.726 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Creating 14 Apex artifacts in Apex DB
Sept 18, 2023 9:53:47 AM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 19 ms.
09:53:48.957 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Error during startup
org.eclipse.jdt.internal.core.nd.db.IndexException: Corrupted database: apex.db
	at org.eclipse.jdt.internal.core.nd.db.Database.databaseCorruptionDetected(Database.java:435)
	at org.eclipse.jdt.internal.core.nd.db.Database.getChunk(Database.java:410)
	at org.eclipse.jdt.internal.core.nd.db.Database.putFreeRecPtr(Database.java:1120)
	at org.eclipse.jdt.internal.core.nd.db.Database.removeBlock(Database.java:998)
	at org.eclipse.jdt.internal.core.nd.db.Database.malloc(Database.java:493)
	at org.eclipse.jdt.internal.core.nd.db.ShortString.<init>(ShortString.java:43)
	at org.eclipse.jdt.internal.core.nd.db.Database.newString(Database.java:1212)
	at org.eclipse.jdt.internal.core.nd.field.FieldSearchKey.put(FieldSearchKey.java:65)
	at org.eclipse.jdt.internal.core.nd.field.FieldSearchKey.put(FieldSearchKey.java:54)
	at apex.jorje.lsp.impl.index.node.ApexResourceFile.setFilename(ApexResourceFile.java:79)
	at apex.jorje.lsp.impl.index.ApexIndexer.insertTypeInfo(ApexIndexer.java:650)
	at apex.jorje.lsp.impl.index.ApexIndexer.insertCodeUnit(ApexIndexer.java:288)
	at apex.jorje.lsp.impl.index.ApexIndexer.buildCacheInternal(ApexIndexer.java:220)
	at apex.jorje.lsp.impl.index.ApexIndexer.buildCache(ApexIndexer.java:252)
	at apex.jorje.lsp.impl.index.ApexIndexer.lambda$startUp$1(ApexIndexer.java:803)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at apex.jorje.lsp.impl.index.ApexIndexer.startUp(ApexIndexer.java:801)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:230)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
09:53:49.101 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: StandardObjects: 16
09:53:49.102 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: CustomObjects: 0
09:53:49.102 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ApexFiles: 484
09:53:49.102 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ErrorFiles: 164
09:53:49.102 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Total Memory (MB): 140
09:53:49.103 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Used Memory (MB): 46
09:53:49.103 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 1467 ms.

```

**Comment by peternhale** [comment]
Hi @rob-baillie-ortoo, 

Your assertion is correct, previous failure with JDK 11 left the apex.db in a bad state.
Please shutdown vscode, remove the folder `.sfdx/tools/246` and its contents and start vscode.

**Comment by bobalicious** [comment]
Thanks.  That looks like it has done the job.
