### ISSUE TITLE
While using the Replay Debugger, I constantly get the error message "Apex language server could not provide information about valid breakpoints."

### ISSUE THREAD

**Issue by lemmingworks** [forcedotcom/salesforcedx-vscode#5147]
### Summary

While using the Replay Debugger, I constantly get the error message "Apex language server could not provide information about valid breakpoints."

### Steps To Reproduce:

1. Execute "Refresh SObject Definitions" command.
2. Execute the "Turn on Debug Log for Replay Debugger" command.
3. Download log into my VSCode.
4. Execute the "Launch Apex Replay Debugger for Current File" command for the downloaded debug log.

### Expected result

The Apex Replay Debugger should have started.

### Actual result

A "Apex language server could not provide information about valid breakpoints." message pops up.

### Additional information

I had a look at the Apex Language Server output in VSCode (see below), which shows that it threw an "Error trying to get line breakpoint info java.lang.IllegalStateException: Duplicate field: StorageUnitPlatformEvents" error.

I have checked in the code where the "StorageUnitPlatformEvents" variable is used (it is only used in a single class), and there aren't any issues. For instance that code works correctly, and all unit tests run correctly against it.

There aren't any breakpoints or checkpoints against the org, so I don't understand what the issue is or how to resolve this issue. I have had a lot of issues with the Replay Debugger, which is a shame because it is so useful when it works. I'd love to know how to fix this. Thanks.

This is the Apex Language Server output found in VSCode:

10:41:41.683 [pool-1-thread-1] ERROR a.j.l.impl.debug.ApexDebuggerService - Error trying to get line breakpoint info
java.lang.IllegalStateException: Duplicate field: StorageUnitPlatformEvents
	at apex.common.base.Result.throwIfError(Result.java:112)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.create(VirtualFieldTableInitializer.java:59)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.get(VirtualFieldTableInitializer.java:104)
	at apex.jorje.lsp.impl.index.symbol.VirtualFieldTableInitializer.get(VirtualFieldTableInitializer.java:38)
	at apex.common.base.Initializers$MemoizingInitializer.get(Initializers.java:74)
	at apex.jorje.semantic.symbol.type.AbstractTypeInfo.fields(AbstractTypeInfo.java:132)
	at apex.jorje.semantic.symbol.resolver.VariableResolver.lookup(VariableResolver.java:171)
	at apex.jorje.semantic.symbol.resolver.VariableResolver.lookup(VariableResolver.java:129)
	at apex.jorje.semantic.symbol.resolver.VariableResolver.lookupStatic(VariableResolver.java:373)
	at apex.jorje.semantic.symbol.resolver.StandardSymbolResolver.lookupStaticVariableInfo(StandardSymbolResolver.java:252)
	at apex.jorje.semantic.ast.expression.ReferenceExpression.validate(ReferenceExpression.java:201)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.validate(MethodCallExpression.java:171)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.validate(MethodCallExpression.java:175)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.validate(ExpressionStatement.java:60)
	at apex.jorje.semantic.ast.statement.BlockStatement.validate(BlockStatement.java:154)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.validate(MethodBlockStatement.java:82)
	at apex.jorje.semantic.ast.member.Method.validate(Method.java:172)
	at apex.jorje.semantic.ast.compilation.UserClass.validate(UserClass.java:183)
	at apex.jorje.semantic.compiler.CodeUnit.validate(CodeUnit.java:220)
	at apex.jorje.semantic.compiler.CompilerOperations$ValidateOperation.invoke(CompilerOperations.java:96)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processFirstStage(CompilerStageProcessor.java:136)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processToStage(CompilerStageProcessor.java:105)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:120)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:149)
	at apex.jorje.lsp.impl.services.StandardCompilerService.fetchCodeUnit(StandardCompilerService.java:236)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:94)
	at apex.jorje.lsp.impl.debug.ApexDebuggerService.lambda$lineBreakpoints$0(ApexDebuggerService.java:90)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.debug.ApexDebuggerService.lineBreakpoints(ApexDebuggerService.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Salesforce Extension Version in VS Code**:
v58.16

**SFDX CLI Version**:
@salesforce/cli/2.9.8

**OS and version**:
MacOS Monterey 12.6.8

**VS Code version**:
1.83.0

**Comment by peternhale** [comment]
@lemmingworks Could be a corrupt apex index db. Can you try these steps:
* close vscode
* delete the folder `.sfdx\tools\246`
* open vscode
* wait for Apex status bar entry reaches 'Indexing done'
* try the steps again

**Comment by lemmingworks** [comment]
Hi @peternhale, thank you for your response.

Re-saving the Apex class containing the variable mentioned in the "Duplicate field" error in the Apex Language Server output seemed to fix it in the end.

**Comment by peternhale** [comment]
@lemmingworks thanks for letting me know. I am going to close this issue.
