### ISSUE TITLE
Run All Test button is stopped showing on vscode for Salesforce project

### ISSUE THREAD

**Issue by gpatelii** [forcedotcom/salesforcedx-vscode#5241]
The run all test was working since last 2 years and suddenly in the middle of the afternoon it stopped appearing.

I have re-installed the vs code 3 times with Salesforce extension pack and also went to the lower version but still i am getting below error when i open any test class

2023-11-17 10:04:32.050 [error] [salesforce.salesforcedx-vscode-apex] provider FAILED
2023-11-17 10:04:32.050 [error] Error: Internal error.
	at Dn (/Users/patelg5/.vscode/extensions/salesforce.salesforcedx-vscode-apex-59.5.1/dist/index.js:226:233)
	at In (/Users/patelg5/.vscode/extensions/salesforce.salesforcedx-vscode-apex-59.5.1/dist/index.js:225:7399)
	at rn (/Users/patelg5/.vscode/extensions/salesforce.salesforcedx-vscode-apex-59.5.1/dist/index.js:225:7522)
	at Immediate.<anonymous> (/Users/patelg5/.vscode/extensions/salesforce.salesforcedx-vscode-apex-59.5.1/dist/index.js:225:7286)
	at process.processImmediate (node:internal/timers:476:21)

**Comment by peternhale** [comment]
Good day @gpatelii to better diagnose this issue would you mind providing the following:

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Additional information

- Salesforce Extension Version in VS Code

- SFDX CLI Version

- OS and version

- VS Code version

**Comment by daphne-sfdc** [comment]
Hi @gpatelii, We have not received your response to this issue in the past week, so I'm going to assume it has been resolved and close it as completed. If you are still seeing the issue, we just released v59.7.0 of the extensions, so please update your extensions to the latest version and try again.  Then feel free to reopen if the issue still persists.
