### ISSUE TITLE
Error while updating 'Apex' extension.

### ISSUE THREAD

**Issue by vincekruger** [forcedotcom/salesforcedx-vscode#5291]
### Summary

The following extensions fail to update to the latest version.
- Apex
- Aura Components
- Lightning Web Components

### Steps To Reproduce:

Try to update to the latest version.

### Expected result

Should update.

### Actual result

Fails to update.

```
2023-12-21 19:28:32.868 [warning] [mainThreadStorage] large extension state detected (extensionId: salesforce.salesforcedx-vscode-core, global: true): 1124.9384765625kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.

2023-12-21 19:30:12.834 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at d.download (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:82:192)
    at async te.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:121718)
    at async te.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:119735)
```

<img width="363" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/360833/57d3a982-1e4e-4bcb-a9a8-86452ac5e908">

**Salesforce Extension Version in VS Code**: 59.8.0

**SFDX CLI Version**: sfdx-cli/7.209.6 darwin-arm64 node-v18.15.0

**OS and version**:  macOS 14.2.1 (23C71)

**VS Code version**: 1.85.1

**Comment by peternhale** [comment]
@vincekruger could you try uninstalling the CLI extension pack and then install from scratch?

**Comment by vincekruger** [comment]
Have tried this already, no luck.

**Comment by peternhale** [comment]
@vincekruger let's try:
* exit vscode
* remove contents from `~/.vscode/extensions` that start with `salesforce.salesforcedx`
* start vscode
* check running extensions to be sure that all CLI extensions are no longer running
* Install CLI extension pack

**Comment by vincekruger** [comment]
I have the same issue on my iMac.

```
2023-12-22 11:59:55.911 [error] Error: end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:78814
    at Array.reduce (<anonymous>)
    at E (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:78800)
    at Y.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:70475)
    at async Y.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:68161)
    at async /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:64829
    at async Promise.allSettled (index 0)
    at async Y.I (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:64776)
    at async Y.installGalleryExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:63225)
    at async Y.installFromGallery (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:62546)
2023-12-22 11:59:55.924 [error] end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found: Error: end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:78814
    at Array.reduce (<anonymous>)
    at E (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:78800)
    at Y.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:70475)
    at async Y.J (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:68161)
    at async /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:64829
    at async Promise.allSettled (index 0)
    at async Y.I (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:64776)
    at async Y.installGalleryExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:63225)
    at async Y.installFromGallery (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:100:62546)
```

**Comment by vincekruger** [comment]
The issue must be related to something else because via the CLI it worked.

```
code --install-extension salesforce.salesforcedx-vscode
Installing extensions...
Installing extension 'salesforce.salesforcedx-vscode'...
Extension 'salesforce.salesforcedx-vscode' v59.9.0 was successfully installed.
```

**Comment by mingxuanzhangsfdx** [comment]
Thank you @vincekruger , saw a bunch of similar [issues](https://github.com/microsoft/vscode/issues/42229) reported.

Looks like there is something wrong with VS Code. Workarounds are installing it manually with vsixes or through CLI you did. I will close this issue and feel free to reopen it if you have further questions.
