### ISSUE TITLE
Apex server fails to start when starting vs code

### ISSUE THREAD

**Issue by TomArena** [forcedotcom/salesforcedx-vscode#5412]
Type: <b>Bug</b>

I've updated npm and sf. The error occurs when the extension starts.

Exception in thread "main" java.lang.InternalError: Failed to load default.policy
	at java.base/sun.security.provider.PolicyFile.initDefaultPolicy(PolicyFile.java:504)
	at java.base/sun.security.provider.PolicyFile$2.run(PolicyFile.java:348)
	at java.base/sun.security.provider.PolicyFile$2.run(PolicyFile.java:345)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/sun.security.provider.PolicyFile.initPolicyFile(PolicyFile.java:345)
	at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:338)
	at java.base/sun.security.provider.PolicyFile.<init>(PolicyFile.java:292)
	at java.base/java.security.Policy.loadPolicyProvider(Policy.java:221)
	at java.base/java.security.Policy.getPolicyNoCheck(Policy.java:191)
	at java.base/java.security.ProtectionDomain.implies(ProtectionDomain.java:325)
	at java.base/java.security.ProtectionDomain.impliesWithAltFilePerm(ProtectionDomain.java:357)
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:463)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at ch.qos.logback.core.util.Loader$1.run(Loader.java:48)
	at ch.qos.logback.core.util.Loader$1.run(Loader.java:45)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at ch.qos.logback.core.util.Loader.<clinit>(Loader.java:45)
	at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java:119)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at apex.jorje.lsp.ApexLanguageServerLauncher.<clinit>(ApexLanguageServerLauncher.java:46)
Caused by: java.nio.file.NoSuchFileException: C:\Program Files\Java\jdk-17\lib\security\default.policy
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2955)
	at java.base/sun.security.provider.PolicyFile.initDefaultPolicy(PolicyFile.java:493)
	... 26 more
[Error - 9:29:56 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:29:56 AM] Connection to server got closed. Server will not be restarted.
[Error - 9:29:56 AM] Apex Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:29:56 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

Extension version: 59.17.0
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.51GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/TomArena/Documents/Development/Salesforce/Complete-INSITE --crash-reporter-id 20b0b15c-850a-4901-9779-b4b12230953b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b5d27386:30958190
3ef8e399:30949928
bg6jg535:30958357

```

</details>

**Comment by peternhale** [comment]
Hi @TomArena the stack trace above indicates that your java installation is missing the `default.policy` typically found in folder `lib\security\` in the java installation directory.

You could try reinstalling java on your machine to see if that helps.

**Comment by TomArena** [comment]
I uninstalled all versions of java, deleted the Java folder, and
reinstalled. This fixed the issue. Thank you. This can be closed. Not sure
where the Java 17 version came from.

On Friday, Feb 9, 2024, 2:24 PM, wrote:

> Hi @TomArena the stack trace above indicates that your java installation
is missing the `default.policy` typically found in folder `lib\security\`
in the java installation directory. You could try reinstalling java on your
machine to see if that helps. -- Reply to this email directly or view it on
GitHub:
https://github.com/forcedotcom/salesforcedx-vscode/issues/5412#issuecomment-1936683461
You are receiving this because you were mentioned. Message ID:


*Tom Arena*
