### ISSUE TITLE
SF Code deploy not working

### ISSUE THREAD

**Issue by debprotim** [forcedotcom/salesforcedx-vscode#5521]
Type: <b>Bug</b>

We are successfully able to authenticate an org, but deploying a code runs into a neverending process. and the console log is filled with errors.

TypeError: msg.socket.cork is not a function
	at write_ (node:_http_outgoing:930:16)
	at ClientRequest.write (node:_http_outgoing:834:15)
	at PassThrough.ondata (node:internal/streams/readable:766:22)
	at PassThrough.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at PassThrough.push (node:internal/streams/readable:234:10)
	at node:internal/streams/transform:182:12
	at PassThrough._transform (node:internal/streams/passthrough:46:3)
	at PassThrough._write (node:internal/streams/transform:175:8)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at PassThrough.write (node:internal/streams/writable:337:10)
	at DuplexifiedStream._write (c:\Users\sealde\.vscode\extensions\salesforce.salesforcedx-vscode-core-60.5.1\node_modules\jsforce\lib\util\stream.js:88:20)
	at writeOrBuffer (node:internal/streams/writable:392:12)
	at _write (node:internal/streams/writable:333:10)
	at DuplexifiedStream.end (node:internal/streams/writable:612:17)
	at Timeout._onTimeout (c:\Users\sealde\.vscode\extensions\salesforce.salesforcedx-vscode-core-60.5.1\node_modules\jsforce\lib\request-helper.js:43:16)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)

Extension version: 60.5.1
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|24.00GB (9.72GB free)|
|Process Argv|--crash-reporter-id e0184630-ca6f-4c06-b72e-24a6f74d1f01|
|Screen Reader|no|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by daphne-sfdc** [comment]
Hi @debprotim, We previously received an issue with the same error message https://github.com/forcedotcom/salesforcedx-vscode/issues/5025, and the issue was in the settings.  Can you check both your User and Workspace settings and remove `"http.proxySupport": "on"` from both `settings.json` files if that line is present?

**Comment by debprotim** [comment]
Thanks @daphne-sfdc, you are a life savior. It just fixed my issue. Please don't close this case as of now, I need to see if this fixes issue for rest of my team.

**Comment by daphne-sfdc** [comment]
@debprotim I'm very happy to know that this worked for you!  Sure, go ahead and confirm with your team, and let me know once everything's good and you're ready for this to be closed. 😁

**Comment by debprotim** [comment]
You may close this bug now, it is resolved on our end. Thank you very much for all the help.
