### ISSUE TITLE
"Go to Definition" and "Peek Definition" not working

### ISSUE THREAD

**Issue by maruchymurphy79** [forcedotcom/salesforcedx-vscode#557]
### Summary

"Go to Definition" and "Peek Definition" not working when the method is in a different class.

### Steps To Reproduce:

1.  Right click on the method you want to see the definition.
2.  Select "Go to Definition" from menu.

### Expected result

New class opened with the corresponding method we would like to see the definition. 

### Actual result

A message is displayed "No definition found for 'Method name'".
![sample](https://user-images.githubusercontent.com/28985946/44061122-18ea2bf0-9f25-11e8-9912-50163118e415.png)

**VS Code Version**: 1.26.0

**OS and version**: W10

**Comment by lcampos** [comment]
Hi @maruchymurphy79 thanks for reporting this. I've been trying to replicate the issue on my side and the only way I was able to was by having an "invalid" method (the interface is incorrect) or using a method from a utility that I do not have on my local project. This is because we only use the code you have on your local project to find definitions/references used in "Go To Definition" & "Find All References".

Can you confirm if that code deploys successfully to a scratch org and that the helper class is part of your local project ?

Thanks

**Comment by maruchymurphy79** [comment]
Hi @lcampos:
Thanks for getting back to me really quick. Our organization is not in DX yet, so we don't have scratch org. We have a local folder connected to Github. We should move to DX in a couple of months. However, I have been using VS Code for more than a month and it was working for me in the previous version. Just after the upgrade it is not working. Please, confirm if the feature is only available for scratch org and if that is the case if you have any work around in the meantime.
Thanks!

**Comment by vazexqi** [comment]
@maruchymurphy79 - This feature of the Apex language server is not specific to just scratch orgs. As long as the source format is in the proper form (has a sfdx-project.json, the classes are organized properly, etc) it should work.

Due to the way we are using the Apex compiler (which is not a fault-tolerant incremental compiler), sometimes an error in a different file could cause some issue with go-to-defintion and find-all-references.

Since you mentioned this working a while back for you, could you let us know if there are any errors (see https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server#are-there-any-errors-from-the-apex-language-server).

**Comment by keirbowden** [comment]
Chiming in :)

@vazexqi I'm not using the Salesforce DX directory structure, instead I have the metadata API structure (src/classes) - does this satisfy "the classes are organized properly," requirement?

I have an error from the language server, but it seems to come a few seconds after I try to go to the definition. I get the following output:

```
16:59:35.429 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Aug 20, 2018 4:59:35 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
WARNING: Unsupported notification method: initialized
Aug 20, 2018 4:59:35 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7403062 shorts which is 14MB not including array overhead. Removed 6746470 shorts which is 12MB not counting array overhead. Took 8 ms.
16:59:37.376 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
16:59:37.380 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
16:59:37.720 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types.
16:59:37.720 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 2292 ms.
16:59:37.735 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types took 14 ms.
```

Then a few seconds after a go to definition I get:

```
Aug 20, 2018 5:00:23 PM apex.jorje.semantic.compiler.CodeUnit additionalValidate
INFO: unexpected error during apex additional validate:
```

followed by the contents of the class that I am currently editing, followed by:

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.getMethod(MethodCallExpression.java:504)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy$LocalSymbolVisitor.visitEnd(StandardSymbolsDefinitionStrategy.java:249)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy$LocalSymbolVisitor.visitEnd(StandardSymbolsDefinitionStrategy.java:117)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.traverse(MethodCallExpression.java:157)
	at apex.jorje.semantic.ast.statement.VariableDeclaration.traverse(VariableDeclaration.java:82)
	at apex.jorje.semantic.ast.statement.VariableDeclarationStatements.traverse(VariableDeclarationStatements.java:88)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:141)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:76)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:128)
	at apex.jorje.semantic.compiler.CodeUnit.additionalValidate(CodeUnit.java:291)
	at apex.jorje.semantic.compiler.CompilerOperations$AdditionalValidateOperation.invoke(CompilerOperations.java:117)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processFirstStage(CompilerStageProcessor.java:133)
	at apex.jorje.semantic.compiler.CompilerStageProcessor.processToStage(CompilerStageProcessor.java:103)
	at apex.jorje.semantic.compiler.ApexCompiler.compile(ApexCompiler.java:124)
	at apex.jorje.lsp.impl.services.StandardCompilerService.compile(StandardCompilerService.java:136)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy.lambda$provideDefinition$0(StandardSymbolsDefinitionStrategy.java:106)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy.provideDefinition(StandardSymbolsDefinitionStrategy.java:98)
	at apex.jorje.lsp.impl.definition.ApexDefinitionStrategyAggregator.provideDefinition(ApexDefinitionStrategyAggregator.java:61)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$definition$1(StandardTextDocumentService.java:126)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by maruchymurphy79** [comment]
@vazexqi I have no errors and I have the metadata API structure (src/classes).

**Comment by vazexqi** [comment]
This might be related to https://github.com/forcedotcom/salesforcedx-vscode/issues/587. The error seems to be the same. There is already a customer case on this where we can see the code to repro. Let's use that bug to track for now.

**Comment by vazexqi** [comment]
@maruchymurphy79 - This is indeed related to #587. The stack trace

``` 
ava.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.getMethod(MethodCallExpression.java:504)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy$LocalSymbolVisitor.visitEnd(StandardSymbolsDefinitionStrategy.java:249)
	at apex.jorje.lsp.impl.definition.StandardSymbolsDefinitionStrategy$LocalSymbolVisitor.visitEnd(StandardSymbolsDefinitionStrategy.java:117)
```
 is the same.

I have a fix already (you can see #587). Its going out as v43.14.0 this Thursday.

**Comment by maruchymurphy79** [comment]
I don't think this is the same issue. I'm not getting any null exception. Actually I don't have any error. 
![capture](https://user-images.githubusercontent.com/28985946/46383712-c6028400-c67f-11e8-938b-1e91c580d107.PNG)
Also, I have recently changed to the new manifest structure and still "Go to Definition" and "Peek Definition" are not working.

**Comment by maruchymurphy79** [comment]
@vazexqi Yes, I'm on 43.17.0. I noticed that it works just if the method is static.
