### ISSUE TITLE
Latest (61.2) SOQL & APEX extension fail to activate with recent decomposed element features

### ISSUE THREAD

**Issue by KevinGossentCap** [forcedotcom/salesforcedx-vscode#5664]
### Summary

The CLI introduced a beta feature to decompose more components like the Source format had done with Objects years ago.
It was previously working with extensions but it's now crashing with the latest versions (and the latest-rc of the CLI)

### Steps To Reproduce:

1.  modify any existing sfdx-project.json to add the option like this one : "sourceBehaviorOptions": ["decomposeCustomLabelsBeta"]
1.  reload the extensions or the window
1.  see the running extensions screen and the never ending "activating" statut of 4 extensions

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information
error from extension host in VSCode

```
2024-06-27 11:25:49.610 [error] Error: Failed to load preset decomposeCustomLabelsBeta in c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\presets\decomposeCustomLabelsBeta.json
	at loadPreset (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:291:110473)
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:291:109892
	at Array.reduce (<anonymous>)
	at loadVariants (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:291:109853)
	at getEffectiveRegistry (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:291:109281)
	at new RegistryAccess (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:303:237)
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:339:138
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:351:4260
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:375:2722
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:387:1291
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:423:2085
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:435:1140
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:649:4250
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:661:8569
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:674:3540
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:686:6959
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:8493
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:21331
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:21919
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:22807
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:23078
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:776:26424
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:1614
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:6337
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:6617
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:14085
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:15373
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:22272
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:778:23574
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:786:4802
	at c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1:378
	at Object.<anonymous> (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.2.1\dist\index.js:1304:8046)
	at o._compile (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
	at Module.load (node:internal/modules/cjs/loader:1098:32)
	at Module._load (node:internal/modules/cjs/loader:945:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at E._load (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:5901)
	at n._load (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:30787)
	at t._load (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:33074)
	at Module.require (node:internal/modules/cjs/loader:1122:19)
	at Module.patchedRequire [as require] (c:\Users\wh6533\.vscode\extensions\salesforce.salesforcedx-vscode-core-61.2.1\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (node:internal/modules/helpers:130:18)
	at Function.i [as __$__nodeRequire] (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\loader.js:5:98)
	at u.xb (c:\Users\wh6533\AppData\Local\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:31966)
	at async Promise.all (index 0)
```

**Salesforce Extension Version in VS Code**: 61.1

**Salesforce CLI Version**: @salesforce/cli/2.48.6 win32-x64 node-v20.15.0
```
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.48.6",
  "nodeVersion": "node-v20.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\wh6533\\AppData\\Local\\Programs\\node-v20.12.0-win-x64\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.4 (core)",
    "@oclif/plugin-commands 4.0.4 (core)",
    "@oclif/plugin-help 6.2.3 (core)",
    "@oclif/plugin-not-found 3.2.6 (core)",
    "@oclif/plugin-plugins 5.3.2 (core)",
    "@oclif/plugin-search 1.2.0 (core)",
    "@oclif/plugin-update 4.4.3 (core)",
    "@oclif/plugin-version 2.2.4 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.6 (core)",
    "@oclif/plugin-which 3.2.4 (core)",
    "@salesforce/cli 2.48.6 (core)",
    "apex 3.2.0 (core)",
    "auth 3.6.27 (core)",
    "data 3.5.2 (core)",
    "deploy-retrieve 3.9.9 (core)",
    "info 3.3.11 (core)",
    "limits 3.3.15 (core)",
    "marketplace 1.2.17 (core)",
    "org 4.3.0 (core)",
    "packaging 2.6.1 (core)",
    "schema 3.3.16 (core)",
    "settings 2.3.6 (core)",
    "sobject 1.4.14 (core)",
    "source 3.4.8 (core)",
    "telemetry 3.5.1 (core)",
    "templates 56.3.0 (core)",
    "trust 3.7.10 (core)",
    "user 3.5.17 (core)",
    "@salesforce/sfdx-scanner 4.3.0 (user) published 1 days ago (Tue Jun 25 2024)",
    "sfdx-kgo-plugin 1.4.8 (user) published 76 days ago (Thu Apr 11 2024)"
  ]
}
```
**OS and version**: windows 10 64bit & code builder

**VS Code version**: test and same with 1.83.1 & 1.90.2

**Most recent version of the extensions where this was working**: 61.1

**Comment by mingxuanzhangsfdx** [comment]
Hi @KevinGossentCap Thanks for reporting this. We are actively working on fixing it. The current workaround is to either downgrade extensions to v61.1.2 or disable the setting for now. We really appreciate your report.

**Comment by daphne-sfdc** [comment]
Closing this issue as v61.4.0 of the Salesforce Extensions for VSCode has been released.
