### ISSUE TITLE
Unusually high java process CPU usage

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#641]
### Summary

This seems to happen when using the extension to connect to a sandbox with a fairly big apex codebase (66% of total apex "space" used). But I'm not sure if it happens with smaller codebases.

### Steps To Reproduce:

1. Create test class.
2. Retrieve it.
3. Deploy it.
4. Process should be now eating ~300% of CPU resources.

![screen shot 2018-09-18 at 11 53 03](https://user-images.githubusercontent.com/6956403/45696215-76796f80-bb39-11e8-8dae-f8f81c056a00.png)

![screen shot 2018-09-18 at 11 53 16](https://user-images.githubusercontent.com/6956403/45696213-74afac00-bb39-11e8-9ef7-8f46595a16bd.png)

### Expected result

Java process to chew up a huge amount of CPU time only when running commands, like on extension start up, but then go back to not using that much CPU time, leaving Chrome to be the huge villain here.

### Actual result

Java process chews up 200~400% of CPU % even when not being used, compared to the biggest monster I usually have running (Google Chrome) eating up to 40% of CPU %.

### Additional information

The screenshot below shows how much the java process is keeping the CPU busy in my Macbook. The chart starts with the extension on idle (just VSCode open with 4 or 5 classes, not running anything, no big deal).

Then I proceed to close VSCode and kill the java process through Activity Monitor, and the blue lines go down completely. Then I proceed to open VSCode again with my project, and the chart goes crazy once more. It goes up on start up, and when running some command (like running tests or retrieving/deploying things). And then goes back to normal.

![screen shot 2018-09-17 at 17 59 35](https://user-images.githubusercontent.com/6956403/45694681-2c42bf00-bb36-11e8-8f43-b269cf28c2a1.png)

The thing is that at some point, when a certain command is executed, the java process seems to get stuck and unable to kill some background thread/process/task. The extension still works, but slowing my machine down.

### Workaround

Close VSCode, kill the java process, and restart the editor.

**VS Code Version**:

1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64

**SFDX CLI Version**: "sfdx-cli/6.31.0-32aa4b4408 (darwin-x64) node-v8.9.4", with the plugin "salesforcedx 44.0.14 (pre-release)"

**OS and version**: macOS High Sierra 10.13.6 (17G65)

**Comment by renatoliveira** [comment]
The `output` tab on VSCode shows lots of repeated lines of the same error after force quitting the java process through Activity Monitor:

    [Error - 11:56:07 AM] Request textDocument/codeLens failed.
    Error: Connection got disposed.
        at Object.dispose (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
        at Object.dispose (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-languageclient/lib/client.js:57:35)
        at LanguageClient.handleConnectionClosed (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
        at LanguageClient.handleConnectionClosed (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-languageclient/lib/main.js:106:15)
        at closeHandler (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
        at CallbackList.invoke (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
        at Emitter.fire (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
        at closeHandler (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
        at CallbackList.invoke (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
        at Emitter.fire (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
        at StreamMessageWriter.AbstractMessageWriter.fireClose (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
        at Socket.<anonymous> (/Users/renatoliveira/.vscode/extensions/salesforce.salesforcedx-vscode-apex-43.16.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by vazexqi** [comment]
This is unfortunate. We do need more details so we can reproduce. Are you able to do either of the following (in preferred order):

1. Could you open a support ticket with Salesforce so that we can have log-in as access to your org to pull the source to reproduce this?
1. Are you comfortable using Java tools (e.g., https://dzone.com/articles/how-to-take-thread-dumps-7-options) to capture the thread dumps for us so that we can take  a closer look?

**Comment by renatoliveira** [comment]
If I understood correctly, using `jstack` takes thread dumps and automatically kills the process. If that's the case, then I'll update with the stack as soon as I can get the issue to show up again.

The org in question is a customer's sandbox environment, which is being actively used as a development environment. Fortunately they have Premier Support. I'll raise the case with support, but what do I tell them? Or can I post the case number here with the dump?

**Comment by vazexqi** [comment]
If you go with option 2, raise the case with support and then tell them to assign it to Platform Dev Tools (per the conversation here) — give them a link to this particular comment from _me_. I've done this before with https://github.com/forcedotcom/salesforcedx-vscode/issues/587#issuecomment-414707414

**Comment by renatoliveira** [comment]
@vazexqi I've raised a case with support. Case Number 20155542, and the dump is attached to it.

I've also noted that this issue seems to be unrelated to metadata retrieval or deployment. Seems to have started when I started typing code on the editor (and after a couple of minutes autocomplete was not working anymore, and the java process was stuck on 200%+ CPU usage).

Let me know if there's something else I can help with.

**Comment by vazexqi** [comment]
@renatoliveira - I just got the case today and I'm trying to reproduce it. So far I've pulled down all the apex classes, apex triggers from your org. 

I then tried the following:

1. I tried to invoke code completion, code navigation, etc and I don't see any spikes in CPU.
1. I tried to create a new simple test class _locally_ (I didn't push/deploy) and I don't see any spikes in CPU.

Here's what my process explorer look like from VS Code > Help > Open Process Explorer. Java is on the low CPU.

![screen shot 2018-09-25 at 2 31 15 pm](https://user-images.githubusercontent.com/54414/46044468-ac859900-c0cf-11e8-85db-e7dc9e890f03.png)


Your repro steps mentioned

1. Create test class. *Where did you create this class?*
1. Retrieve it. *Did you create the class from the server?*
1. Deploy it. *I didn't do any deployments since I don't want to disrupt anything on your side*
1. Process should be now eating ~300% of CPU resources.

**Comment by nkadis** [comment]
I d the exact same problem. I don't know exactly what this is but what I've noticed is that this occurred when trying to get code-completion suggestions. This caused the plugin to throw a really long error message (also containing all the code from within my currently edited file).

I think I got the problem to stop occurring, though. I just uninstalled Java and then reinstalled, and fortunately now it doesn't stay at 270+% usage. Although, this does not stop the plugin from using up 270+% of the CPU. In my case, my code base is really large, so I think this is why code-completion suggestions still cause CPU usage spikes, but at least it returns back to normal (see image below).

![screen shot 2018-09-27 at 09 59 04](https://user-images.githubusercontent.com/12812036/46134972-0c00b780-c23c-11e8-9e7e-46efddf8294c.png)

Hope this helps.

**Comment by renatoliveira** [comment]
This is the exact same error that I got @nkadis. I thought that all the messages were the same, but the first error on the stack is different from the other ones. Should've posted that before. Sorry about that!

**Comment by vazexqi** [comment]
@nkadis — Your stack trace is a bit different but it at least shows a proper bug. When that bug occurs it took down the language server (hence all the connection lost logs). Since it’s a `NullPointerException`, we can guard against that in our `ApexCodeLenseProvider`. 

I am not sure if this would help @renatoliviera case but we can try this fix first.

**Comment by vazexqi** [comment]
Actually, looking more closely at the stacktrace

```
10:14:23.847 [ForkJoinPool.commonPool-worker-2] ERROR a.j.l.i.c.CodeLensesProviderAggregator - Encountered an error with code lens provider apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider@383dc82c
java.lang.IllegalArgumentException: expected one element but was:
<!-- The contents of the file it crashed in -->
at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:316)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
	at apex.jorje.lsp.api.utils.CodeUnits.getMatchingElement(CodeUnits.java:35)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.lambda$provideCodeLenses$0(ApexTestRunCodeLensesProvider.java:88)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.provideCodeLenses(ApexTestRunCodeLensesProvider.java:86)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.lambda$provideCodeLenses$0(CodeLensesProviderAggregator.java:58)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.provideCodeLenses(CodeLensesProviderAggregator.java:56)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeLens$4(StandardTextDocumentService.java:181)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

// What happened between then and now?

[Info  - 12:51:57 PM] Connection to server got closed. Server will restart.
```

It seems that the `IllegalArgumentException` occurred at 10:14:23.847 whereas `[Info  - 12:51:57 PM] Connection to server got closed. Server will restart` happened almost 3 hours later.

The `Connection to server got closed` is the actual culprit. Do you have an idea of what you were doing? I have some theories:

1. Did you do a `git clean -xfd` on that project?
1. Did you manually delete the files in the .sfdx/ folder on that project?
1. Did you open multiple instances of VS code on the same project?
1. Did the laptop go into sleep mode?

**Comment by renatoliveira** [comment]
I can guarantee that I didn't do 1, 2 and 3. Number 4 is possible, however. But I did face this issue even when the laptop didn't go into sleep mode.

I've been working with Lightning Components mostly since then, so I haven't faced this issue anymore to check. Today I wrote some classes and tests, but didn't see this issue happening again.

**Comment by nkadis** [comment]
> // What happened between then and now?
I believe that the `Connection to server got closed` error occurred when I force quit java from Activity Monitor. I did this to stop the cpu from getting fried.

> 1. Did you do a git clean -xfd on that project?
No

>2. Did you manually delete the files in the .sfdx/ folder on that project?
The only thing I removed from the `.sfdx` folder is `.sfdx/tools/apex.db` as per the Troobleshooting section on [Apex Code Editor for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex).
> If you’re not seeing the Apex completion suggestions that you expect, your Apex database might need to be rebuilt. Quit VS Code, and then delete the .sfdx/tools/apex.db file from your project. Then relaunch VS Code, and open an Apex class or trigger. The Apex database rebuilds within about 5 seconds (up to 30 seconds for very large code bases).

> 3. Did you open multiple instances of VS code on the same project?
No

> 4. Did the laptop go into sleep mode?
No

**Comment by shillem** [comment]
I'm also experiencing this problem. Hoping it's going to be of some help I attach the process dump contents of the process that more than a few times goes out of control.

[dump.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2628160/dump.txt)

**Comment by shillem** [comment]
It seems to me that the problem is triggered **while the outline pane is opened**.
If the outline pane is collapsed, no hangs. It's been 2 days now without one, whereas before it was guaranteed it would happen sooner or later.

**Comment by andrewhorwood** [comment]
I'm also experiencing this error. It seems to effect autocompletion, it does not cause application hang (windows). I've tried refreshing sObject Definitions, deleting Apex.db and restarting vscode
```
[ForkJoinPool.commonPool-worker-0] ERROR a.j.l.i.c.CodeLensesProviderAggregator - Encountered an error with code lens provider apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider@35b74c5c
java.lang.IllegalArgumentException: expected one element but was: <File Contents here>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:316)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
	at apex.jorje.lsp.api.utils.CodeUnits.getMatchingElement(CodeUnits.java:35)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.lambda$provideCodeLenses$0(ApexTestRunCodeLensesProvider.java:88)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.provideCodeLenses(ApexTestRunCodeLensesProvider.java:86)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.lambda$provideCodeLenses$0(CodeLensesProviderAggregator.java:58)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.provideCodeLenses(CodeLensesProviderAggregator.java:56)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeLens$7(StandardTextDocumentService.java:186)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by renatoliveira** [comment]
@ntotten I see that you have removed the "in gus" label and also added this issue to the Spring 19 milestone. So it looks like we can expect a fix on the very next Salesforce release, right? 🙏

**Comment by ntotten** [comment]
We are working on a fix for this one as well as working on adding support for OpenJDK 11. We aren't tied to Salesforce releases so the timeline isn't exact. We use those release for planning, but we ship features/fixes whenever they are ready in our weekly releases. 

Regarding the "in-gus" tag, we just stopped using that so that doesn't mean anything. :)

**Comment by renatoliveira** [comment]
Oh? I thought the releases were in sync with the platform's.

Great to know that #398 will be addressed as well.

Good job! 👍
